import Link from "next/link";

const questions = [
  "Where does Culturalyst currently see valuable Hawaiʻi-based creative work becoming difficult to discover, validate, connect, or fund?",
  "Which people are least well served by the ecosystem's current language, categories, application processes, or relationship pathways?",
  "What does Culturalyst already know that repeatedly has to be explained one person or one conversation at a time?",
  "Which next action is hardest for an artist or cultural worker to identify after discovering Culturalyst?",
  "What would make a public resource genuinely useful to Culturalyst rather than simply adding another layer to maintain?",
  "Is there a specific initiative, audience, dataset, or decision where a small prototype would make the opportunity easier to evaluate?",
];

export default function CulturalystConversation(){return <main><RecipientNav/><header id="main-content" tabIndex={-1} className="recipientHero shell"><p className="eyebrow">04 · Conversation brief</p><h1>Start with what<br /><em>Culturalyst knows</em><br />from the field.</h1><p>The conversation should locate one consequential break, the people living with it, the knowledge Culturalyst already holds, and the smallest useful form RN could research or build next.</p></header><section className="fit"><div className="shell fitgrid"><p className="eyebrow">Questions for the room</p><ol className="conversationQuestions">{questions.map((question,index)=><li key={question}><span>0{index+1}</span><p>{question}</p></li>)}</ol></div></section><section className="work shell"><div className="sectionhead"><p className="eyebrow">A useful outcome</p><p>One defined question, one audience, one next artifact.</p></div><div className="answergrid lightAnswers"><section><p className="eyebrow">The question</p><p>A specific ecosystem breakdown worth understanding or changing.</p></section><section><p className="eyebrow">The people</p><p>The artists, cultural workers, institutions, or partners whose experience must shape the work.</p></section><section><p className="eyebrow">The next artifact</p><p>A scoped research brief, visual map, assessment, interactive route, or prototype that makes the next decision easier.</p></section></div></section><footer className="footer"><div className="shell footergrid"><div><p className="eyebrow">Continue the conversation</p><h2>Find the break.<br/><em>Choose the form.</em></h2></div><div className="contact"><a href="https://www.linkedin.com/in/rn-collins" target="_blank" rel="noreferrer">Connect with RN on LinkedIn ↗</a><Link href="/for/culturalyst">Return to the beginning →</Link><Link href="/">Explore all RN work →</Link></div></div></footer></main>}
function RecipientNav(){return <nav className="nav shell" aria-label="Culturalyst view"><Link className="mark" href="/">RN<span>↗</span></Link><div className="navlinks"><Link href="/for/culturalyst">Why RN</Link><Link href="/for/culturalyst/work">Work</Link><Link href="/for/culturalyst/opportunities">Opportunities</Link><Link href="/for/culturalyst/conversation">Conversation</Link></div></nav>}
