import Link from "next/link";
import { CanonicalPage } from "../components/canonical-page";
import { projects } from "../lib/portfolio";
import { getSiteProperty } from "../lib/site-properties";

const featured = ["ownership-platform","flexjd-resource-hub","keiki-robotics"].map((slug)=>projects.find((project)=>project.slug===slug)).filter(Boolean);
const initiatives = ["aloha-ai","institutions-of-one","nsag"].map(getSiteProperty).filter(Boolean);

export default function Home(){return <CanonicalPage>
  <header className="canonicalHero shell"><p className="eyebrow">The practice of Rayven-Nikkita (RN) Collins</p><h1>I work on questions<br/>too messy for a<br/><em>single discipline.</em></h1><p className="canonicalLede">When something important is not working—and no one can quite name why—I research the system, find the gap, make it concrete, and build what is needed next.</p><div className="canonicalActions"><Link className="button" href="/work">See what I have built →</Link><Link className="button secondary" href="/contact">Bring me the problem →</Link></div></header>
  <section className="canonicalBand"><div className="shell canonicalSplit"><p className="eyebrow">You may need RN when</p><div><h2>You know something is wrong.<br/>You do not need another generic answer.</h2><ul className="canonicalList"><li>You can feel the problem, but your organization cannot define it clearly enough to act.</li><li>The research, people, policy, operations, and technology do not line up.</li><li>You have a strategy, but no tool, workflow, resource, or implementation path people can actually use.</li><li>The question crosses disciplines, teams, or institutions—and keeps falling between them.</li></ul></div></div></section>
  <section className="canonicalSection shell"><div className="canonicalSectionHead"><p className="eyebrow">How RN works</p><Link href="/practice">Explore the practice →</Link></div><ol className="methodCards"><li><span>01</span><h3>Study the system</h3></li><li><span>02</span><h3>Find the consequential break</h3></li><li><span>03</span><h3>Make it concrete and visible</h3></li><li><span>04</span><h3>Choose and build the useful form</h3></li></ol></section>
  <section id="work" className="canonicalSection shell"><div className="canonicalSectionHead"><div><p className="eyebrow">Selected proof</p><h2>Different forms.<br/>One underlying practice.</h2></div><Link href="/work">See all selected work →</Link></div><div className="canonicalCards">{featured.map((project)=>project&&<article key={project.slug}><p className="eyebrow">{project.kind} · {project.status}</p><h3>{project.shortTitle}</h3><p>{project.thesis}</p><Link href={`/work/${project.slug}`}>Read case study →</Link></article>)}</div></section>
  <span id="build-atlas" className="compatibilityAnchor" aria-hidden="true"/>
  <section className="canonicalBand"><div className="shell canonicalSplit"><p className="eyebrow">For organizations</p><div><h2>Start with what is actually happening.</h2><p className="bigcopy">I can research the problem, show you what is missing, and work with you to decide whether the next useful thing is a brief, strategy, system, curriculum, prototype, facilitated inquiry, or implementation plan.</p><div className="canonicalActions"><Link href="/for-organizations">See how an engagement can begin →</Link><Link href="/for/culturalyst">View the Culturalyst example →</Link></div><small>For Culturalyst is independently initiated pre-proposal work. It was not commissioned by or produced on behalf of Culturalyst.</small></div></div></section>
  <section className="canonicalSection shell"><div className="canonicalSectionHead"><div><p className="eyebrow">Initiatives</p><h2>Long-running questions<br/>I keep building into.</h2></div><Link href="/initiatives">Explore the initiatives →</Link></div><div className="canonicalCards">{initiatives.map((initiative)=>initiative&&<article key={initiative.id}><p className="eyebrow">{initiative.kind} · {initiative.lifecycle}</p><h3>{initiative.shortName}</h3><p>{initiative.purpose}</p>{initiative.destination&&<Link href={initiative.destination}>Explore initiative →</Link>}</article>)}</div></section>
  <span id="writing" className="compatibilityAnchor" aria-hidden="true"/>
  <section className="canonicalSection shell"><div className="canonicalSectionHead"><div><p className="eyebrow">Published work</p><h2>Reporting, analysis,<br/>science, law, and systems.</h2></div><Link href="/writing">Explore the writing archive →</Link></div></section>
</CanonicalPage>}
