/**
 * The join between the generated inventory and the curated write-ups.
 *
 *   data/builds.json   generated by scripts/regenerate-builds.mjs
 *   lib/build-notes.ts written by hand
 *
 * Pages render from here, so a build that exists and answers is on the site as
 * soon as the script has been run and its write-up added. Nothing on the index
 * is maintained by remembering to add it twice.
 */

import inventory from "../data/builds.json";
import {
  buildNotesByRepo,
  categories,
  type BuildNote,
  type CategoryId,
} from "./build-notes";

export type InventoryRecord = {
  repo: string;
  live: string | null;
  visibility: string;
  repoUrl: string | null;
  githubDescription: string | null;
  pushedAt: string | null;
  httpStatus: number | string;
  renderedWords: number | null;
  reachable: boolean;
  hasNote: boolean;
};

export type Build = BuildNote & {
  live: string;
  repoUrl: string | null;
  sourceVisibility: string;
  lastDeployed: string | null;
  verifiedStatus: number | string;
};

const records = inventory.builds as InventoryRecord[];

export const builds: Build[] = records
  .map((record) => {
    const note = buildNotesByRepo.get(record.repo);
    if (!note || !record.live) return null;
    return {
      ...note,
      live: record.live,
      repoUrl: record.repoUrl,
      sourceVisibility: record.visibility,
      lastDeployed: record.pushedAt,
      verifiedStatus: record.httpStatus,
    } satisfies Build;
  })
  .filter((build): build is Build => build !== null);

/** Builds present in the inventory with no write-up yet. Rendered as a visible gap, never hidden. */
export const undescribed = records.filter((record) => record.reachable && !record.hasNote);

export const excludedFromIndex = inventory.excluded as { repo: string; reason: string }[];

export const inventoryGeneratedAt = inventory.generatedAt as string;
export const inventoryCounts = inventory.counts as {
  repositories: number;
  vercelProjects: number;
  excluded: number;
  published: number;
  unreachable: number;
};

/** Builds cross-listed under the institutional section. Derived, not listed. */
export const institutionalBuilds: Build[] = builds.filter((build) => build.institutional);

export function buildsIn(category: CategoryId): Build[] {
  return builds.filter((build) => build.category === category);
}

export const populatedCategories = categories
  .map((category) => ({ ...category, builds: buildsIn(category.id) }))
  .filter((category) => category.builds.length > 0);

export const statusLabels: Record<BuildNote["statusKind"], string> = {
  live: "Live",
  prototype: "Prototype",
  prelaunch: "Prelaunch",
  paused: "Paused",
  retired: "Retired",
  proposal: "Proposal",
};

/** Case-study slug -> build, for the /work/[slug] pages that have a matching build. */
export const buildByCaseStudy = new Map(
  builds.filter((build) => build.caseStudy).map((build) => [build.caseStudy as string, build]),
);

export function getBuild(repo: string): Build | undefined {
  return builds.find((build) => build.repo === repo);
}

export { categories };
export type { CategoryId, BuildNote };
