export type PublicBuild = {
  slug: string;
  title: string;
  category: string;
  practice: string;
  status: string;
  purpose: string;
  built: string;
  serves: string;
  demonstrates: string;
  live: string;
  /** False when this is evidence nested under a parent practice, not a standalone portfolio count. */
  standalone?: boolean;
  /** False when the audited artifact should not be promoted until its release gates are cleared. */
  promoteLive?: boolean;
  source?: string;
  noticed?: string;
  researched?: string;
  evidence?: string;
  artifacts?: { label: string; href: string }[];
};

export const publicBuilds: PublicBuild[] = [
  {
    slug: "aloha-ai",
    title: "Aloha AI",
    category: "AI strategy + implementation",
    practice: "Aloha AI",
    status: "Live practice platform · active development",
    purpose: "Help organizations find where AI belongs, what should remain human, and how a useful implementation can be governed and maintained.",
    noticed: "Organizations are often pushed from a vague desire to 'use AI' directly into vendor selection or deployment. The missing work is decision architecture: defining the bounded problem, considering non-AI alternatives, identifying affected people, preserving evidence and uncertainty, assigning ownership, and deciding in advance when a pilot should stop or roll back.",
    researched: "Aloha AI organizes that problem through a claim-source-limit-review evidence standard and a path from the actual decision to operating conditions and a preserved decision record. Its current public tool set operationalizes workflow scoping, alternatives and evidence review, vendor comparison, pilot design, ownership, affected-party input, stop conditions, rollback, and scheduled reconsideration rather than treating adoption as a one-time technology purchase.",
    built: "A client-facing strategy and delivery platform spanning decision tools, workflow diagnostics, implementation planning, source-backed resources, clinics, and learning experiences.",
    serves: "Organizations and teams deciding whether, where, and how to implement AI responsibly.",
    demonstrates: "Product architecture, evidence-grounded AI strategy, service design, implementation planning, and the ability to turn advisory work into usable infrastructure.",
    evidence: "The live platform verifies a routed starting experience; open learning and Source Desk surfaces; service, policy, accessibility, procurement, and sponsorship pathways; and four complete browser-local v1 decision aids: the Opportunity Studio at /studio, plus a decision record, a vendor comparison, and a pilot designer at /tools. The tools expose guided prompts, rule-based logic or controlling gates, local persistence, readable results, portable Markdown or JSON output where promised, reset controls, and explicit limits without requiring an account or transmitting entries to Aloha AI. This does not establish completed client engagements, verified source accuracy, enterprise collaboration or synchronization, professional advice, compliance certification, authorization to deploy, or improved organizational outcomes. Aloha AI remains the developing client-facing strategy and build practice; it is distinct from NSAG, although it may build technical infrastructure that implements NSAG work.",
    live: "https://aloha-ai-consulting.vercel.app/",
    source: "https://github.com/rn-collins/aloha-ai-consulting",
  },
  {
    slug: "sovereign-stack",
    title: "Sovereign Stack governance-layer concept",
    category: "AI governance + community authority",
    practice: "Aloha AI",
    status: "Browser-local proposal prototype · independently initiated · release-blocked",
    purpose: "Carry community authority through every layer of an AI system—from purpose and data to models, use, review, and refusal.",
    noticed: "Purple Maiʻa's public work described a technical stack involving local compute, open models, edge hardware, place-based environmental observation, and Indigenous approaches to technology. The design question was whether authority, knowledge boundaries, accountability, withdrawal, and refusal could travel through that technical body in a durable form.",
    researched: "The proposal was grounded in Purple Maiʻa's public descriptions of the Sovereign Stack, KILO, Kānāwai, Kula, Waiw.AI, and Rooted Futures, then organized around the unresolved governance questions a community-authorized process would still have to answer.",
    built: "A governance and learning layer that makes ownership, authority, data, model choice, review, exit, and refusal visible as design decisions rather than afterthoughts.",
    serves: "Communities and institutions evaluating AI systems on their own terms.",
    demonstrates: "Sociotechnical systems thinking, governance architecture, public explanation, and interactive proposal design.",
    evidence: "This is an independently prepared working proposal for discussion with Purple Maiʻa. It is not a Purple Maiʻa product, policy, endorsement, approved protocol, community consent, or community-authorized framework. Purple Maiʻa and relevant community and cultural authorities—not RN—would define the substantive values, standing, knowledge permissions, and approvals.",
    live: "https://sovereign-stack-psi.vercel.app/",
  },
  {
    slug: "ai-build-budget-calculator",
    title: "AI Build Cost Workbench",
    category: "AI planning + lifecycle cost modeling",
    practice: "Aloha AI",
    status: "Live interactive cost-modeling workbench · v2 released August 2026",
    purpose: "Turn an early AI-build idea into a transparent, reviewable scenario spanning implementation labor, model usage, infrastructure, vendors, human operations, uncertainty, and first-year cost.",
    noticed: "Custom AI projects are often discussed as a single price even though discovery, research, architecture, implementation, testing, documentation, launch, and maintenance require different kinds and amounts of labor. That opacity makes early scoping difficult for both a buyer and a builder.",
    researched: "The v2 method draws on cost-estimation practices that emphasize a defined baseline, documented assumptions, ranges, sensitivity, uncertainty, and lifecycle cost. It also incorporates AI-lifecycle review lanes and a dated, editable model-price catalog rather than hiding a universal project-price claim behind a project-type selector.",
    built: "A six-stage browser workbench covering project brief, editable labor architecture, model/API workloads, infrastructure, one-time and recurring costs, named uncertainty drivers, review lanes, specification confidence, cost composition, sensitivity drivers, build and monthly ranges, and first-year cost. Scenarios can be saved locally, shared by URL, printed to PDF, or exported as CSV and JSON.",
    serves: "Founders, creators, independent builders, consultants, prospective buyers, and teams preparing an AI-build discovery or procurement conversation.",
    demonstrates: "Product strategy, lifecycle cost modeling, AI workload economics, transparent assumptions, uncertainty analysis, interaction design, local-first privacy, export architecture, and evidence-linked methodology.",
    evidence: "The canonical v2 production release was verified end to end: example loading, live recalculation, eight-workstream labor modeling, multiple model workloads, persistence across reload, share-link reconstruction, CSV and JSON generation, result composition, methodology/privacy/terms routes, and production security headers. The legacy lead relay remains disabled. Outputs are user-authored planning scenarios rather than quotes or independently validated market benchmarks.",
    live: "https://ai-budget-calc-red.vercel.app/",
  },
  {
    slug: "source-integrity-audit",
    title: "Source Integrity Workbench",
    category: "Evidence + legal operations",
    practice: "Independent",
    status: "Live claim-to-source review workbench · v2 August 2026",
    purpose: "Turn claims and citations into a structured verification ledger, review queue, and portable release packet before publication, filing, or decision.",
    noticed: "AI-assisted and human-authored documents can contain authorities that do not exist, sources that do not support the attributed proposition, outdated law or science, vague attribution, and claims whose confidence exceeds the underlying evidence. A spot check cannot show which claims were actually reviewed.",
    researched: "The method separates claim type, materiality, retrievability, source type, support, contradiction, currency, attribution, conflicts, reviewer responsibility, and disposition instead of inferring source validity from citation markers.",
    built: "A five-stage local-first workbench covering the review brief, claim ledger, source register, claim-level findings, blocker queue, release/qualify/replace/remove/hold/escalate decisions, documentation completeness, browser persistence, and Markdown, CSV, JSON, and print/PDF exports.",
    serves: "Publishers, law firms, researchers, founders, creators, portfolio professionals, and trust-sensitive organizations.",
    demonstrates: "Evidence operations, claim-source mapping, review workflow design, deterministic decision logic, local-first privacy, and portable recordkeeping.",
    evidence: "The canonical v2 production release was browser-verified end to end with a brief, material claim, retrievable source record, qualified support finding, disposition, explanatory note, and generated packet. Its score measures documentation completeness—not truth or source authentication—and legal, clinical, scientific, regulatory, and other high-stakes conclusions still require the appropriate qualified reviewer.",
    live: "https://provenance-verify.vercel.app/",
  },
  {
    slug: "one-person-firm-os",
    title: "One-Person-Firm OS",
    category: "Independent work · practice operating-system design",
    practice: "Institutions of One",
    status: "Live interactive practice-architecture workbench · v2 August 2026",
    purpose: "Design portable operating infrastructure for solo consultants, fractional executives, creators, and portfolio professionals across positioning, delivery, client operations, evidence, administration, and AI-assisted workflows.",
    noticed: "Independent professionals often accumulate disconnected notes, task managers, client records, AI conversations, and automations. The tools exist, but the work of deciding what belongs where, what should happen next, and how the system stays current remains with the operator.",
    researched: "The product maps positioning, relationships, delivery, revenue, evidence, knowledge, administration, and governance before recommending tools. The operating method treats recurring review, portability, sensitive-data boundaries, source control, permissions, and human approval as part of the architecture.",
    built: "A six-stage, local-first Practice Operating Architecture Workbench with a maturity and friction map, editable workflow and tool inventories, governed AI role cards, weekly review builder, prioritized 30-day implementation sequence, five portable data schemas, example mode, browser persistence, and Markdown, JSON, CSV, and print/PDF exports.",
    serves: "Solo consultants, fractional executives, creators, portfolio professionals, and other independent operators.",
    demonstrates: "Operational product design, deterministic assessment logic, independent-work infrastructure, schema design, browser-state engineering, AI governance, and portable product delivery.",
    evidence: "The canonical live site was browser-verified on August 14, 2026. The complete example flow generated a scored friction map, specific priority, recommended architecture, weekly review, five downloadable schemas, and implementation exports; navigation and local persistence passed. The workbench is a planning tool rather than a certification or autonomous operating system. A client-specific configured workspace, migration, and implementation remain separate scoped services.",
    live: "https://opfos-firm.vercel.app/",
  },
  {
    slug: "ai-for-developing-brains",
    title: "AI Use Decision Lab",
    category: "Education + child-centered AI governance",
    practice: "Independent · research, science, design, and AI",
    status: "Live local-first decision-support product · v2 August 2026",
    purpose: "Help families, educators, schools, clinicians, and product teams evaluate one specific child-facing AI use before adoption.",
    noticed: "Families and schools are being asked whether children should use AI as though every tool, task, age, data practice, and level of adult oversight creates the same problem. The practical need is a transparent way to examine the role AI will play, what it may replace, what information it receives, and who remains accountable.",
    researched: "The decision model draws on the American Academy of Pediatrics’ 2026 state-of-the-art review, UNICEF’s child-centered AI guidance, UNESCO’s generative-AI guidance for education, U.S. Department of Education FERPA guidance, the FTC’s amended COPPA Rule, and NIST’s Generative AI Profile. It avoids claiming that longitudinal neurological effects are already settled.",
    built: "A five-stage, age-aware decision lab covering context, AI role, cognitive substitution, adult involvement, consequence level, data and human safeguards, inspectable decision logic, developmental capacities to protect, vendor or school questions, monitoring signals, dated source links, browser persistence, Markdown export, and print/PDF output.",
    serves: "Parents, caregivers, educators, schools, clinicians, youth-serving organizations, and teams designing or procuring child-facing AI.",
    demonstrates: "Developmental-science translation, child-centered AI governance, privacy-aware product design, deterministic decision logic, evidence architecture, risk communication, and local-first implementation.",
    evidence: "The canonical production release was browser-verified with two opposing scenarios: an unsupervised emotional-companion use for a young child was stopped with explicit reasons, while a bounded educational use for an older teen with complete safeguards advanced as a monitored trial. The tool does not diagnose children, certify products, determine legal compliance, or claim settled long-term neurological effects.",
    live: "https://kids-developing-brains.vercel.app/",
  },
  {
    slug: "transform-drug-market-transition-observatory",
    title: "Drug Market Transition Evidence Lab",
    category: "Drug policy + evidence operations",
    practice: "Independent research",
    status: "Live source-anchored policy assessment workbench · v2 August 2026",
    purpose: "Turn an individual policy or market development into a reviewable evidence record instead of implying that an unstaffed archive is continuously monitoring a whole sector.",
    noticed: "A policy announcement is not a market outcome. Transition claims can look successful while health, rights, participation, ownership, Indigenous authority, or environmental consequences remain unknown, mixed, or adverse.",
    researched: "The v2 framework draws on Transform Drug Policy Foundation's practical regulation guides, UNDP's 2025 Development Dimensions of Drug Policy, and the UNODC World Drug Report 2026 data architecture. The original seven-part research demonstration is preserved as a clearly dated July 27, 2026 archive.",
    built: "A source-anchored evidence-record builder with six assessment dimensions—public health, human rights, equity and participation, market power, Indigenous rights, and development and environment. Users classify each dimension as unknown, toward, mixed, or away; add evidence notes; receive a deterministic synthesis; export Markdown; print to PDF; route to primary sources; and inspect the preserved research archive.",
    serves: "Policy researchers, advocates, regulators, funders, journalists, and institutional teams examining whether a drug-market transition is producing public-interest outcomes.",
    demonstrates: "Policy framework operationalization, evidence-state design, transparent synthesis logic, research preservation, and truth-aware product architecture.",
    evidence: "Production deployment and canonical routes were verified after rebuild. The tool does not claim automated monitoring, causal proof, or continuing accuracy of the archived research. Each new record requires a source date, primary URL or identifier, and dimension-level evidence notes; unknown remains a valid result. It is informational and not legal, medical, or policy advice.",
    live: "https://transform-observatory.vercel.app/",
  },
  {
    slug: "zero-to-frontier",
    title: "Zero → Frontier AI Literacy Guide",
    category: "AI literacy + public learning infrastructure",
    practice: "Aloha AI",
    status: "Live source-forward learning system · v2 August 2026",
    purpose: "Help people learn enough AI for their actual context and stakes—not merely consume a generic tour of tools.",
    noticed: "AI education often confuses source presence with freshness, teaches tool tricks without proportional human review, and gives the same path to beginners, builders, students, and decision-makers even though their responsibilities differ.",
    researched: "The v2 learning architecture is informed by UNESCO's human-centred AI competency framework, the NIST AI Risk Management Framework and Generative AI Profile, and the European Commission's context-sensitive approach to AI literacy. The existing history, concepts, techniques, use cases, tools, playbooks, templates, frontier material, and 237-resource library remain the curricular base.",
    built: "A deterministic AI Literacy Route Builder that adapts the curriculum to context, goal, stakes, and available time; assigns proportional human-review rules; links directly into the existing learning sequence; exposes dated freshness limitations on every page; and adds private, browser-only progress tracking across eleven core sections.",
    serves: "Curious adults, students, educators, creators, professionals, founders, managers, and teams that need a structured, risk-aware introduction to AI.",
    demonstrates: "Curriculum architecture, standards translation, deterministic personalization, provenance-aware publishing, accessibility, and privacy-preserving learning-state design.",
    evidence: "The canonical production deployment serves twenty-one public HTML routes plus the shared interactive assets. All public routes returned HTTP 200 after the v2 deployment. The route-builder and shared scripts passed syntax checks. Content is source-forward rather than continuously verified: vendor, model, pricing, legal, privacy, and frontier claims remain dated snapshots and must be rechecked against linked primary sources. A duplicate Vercel project, z2f-live, currently mirrors the same canonical GitHub commit; zero-to-frontier.vercel.app is the public source of truth.",
    live: "https://zero-to-frontier.vercel.app/",
    source: "https://github.com/rn-collins/zero-to-frontier",
  },
  {
    slug: "psych-ops-directory",
    title: "Psych Ops Directory + Source Watch",
    category: "Psychedelic operations + provider due diligence",
    practice: "Independent",
    status: "Live operational directory · v6 August 2026",
    purpose: "Help psychedelic organizations discover operational providers and conduct a structured first-pass diligence review without mistaking directory inclusion for verification.",
    noticed: "The ecosystem’s legal, financial, clinical, insurance, staffing, and research providers are distributed across fields and jurisdictions. A vendor list alone does not help a buyer distinguish documented field presence from current licensure, quality, independence, privacy posture, or organizational fit.",
    researched: "The current directory contains 178 listings across twenty-three categories and three public-evidence tiers. The v6 diligence model is informed by current official license and program resources from Oregon, Colorado, and New Mexico and by NIST’s supplier due-diligence approach. The companion Source Watch separates government-domain discovery from secondary field sources.",
    built: "A searchable directory with category filters, comparisons, CSV export, submissions, correction flags, and a private browser-only due-diligence workspace covering entity standing, licensure, insurance, conflicts, privacy and security, references and complaints, and commercial terms. Users can export a Markdown evidence packet. A companion source watch exposes sweep state and direct source links while labeling every discovery an unreviewed lead.",
    serves: "Psychedelic organizations, operators, researchers, clinicians, founders, and professional-service buyers evaluating operational partners.",
    demonstrates: "Ecosystem taxonomy, evidence-model design, provider-diligence workflows, provenance-aware monitoring, local-first state, and operational knowledge architecture.",
    evidence: "The canonical directory returned HTTP 200 after production deployment and its live API returned 178 records. Search, comparison, CSV, submissions, flags, the diligence workspace, local note persistence, and Markdown export remain available. The companion API returned six completed source categories; the interface has no fallback factual records, filters official-jurisdiction views to government domains, and labels results as unreviewed leads. Directory tiers establish public evidence of field presence only—not endorsement, licensure, safety, quality, financial stability, or fit. Users must verify directly with regulators and providers.",
    live: "https://psych-ops-directory.vercel.app/",
    source: "https://github.com/rn-collins/psych-ops-directory",
  },
  {
    slug: "set-for-life",
    title: "Set for Life Relationship-Building Lab",
    category: "Legal education + career process infrastructure",
    practice: "Independent",
    status: "Live public working lab · v2 August 2026",
    purpose: "Help law students turn relationship-building from vague advice into an observable process they can plan, run, measure, and improve.",
    noticed: "Students without inherited professional networks are often told to network without a target model, evidence standard, message architecture, follow-up state, or feedback loop. The prior site compounded that problem by advertising a paid course and commercial delivery workflow that did not exist.",
    researched: "The v2 release preserves RN Collins’s documented outreach process while distinguishing self-reported outcomes from user expectations. Current LinkedIn guidance informed the safety model: fewer relevant invitations, specific context, alternatives such as following and groups, changing personalization limits, and restrictions for high-volume or automated behavior.",
    built: "A no-account, browser-private Relationship-Building Lab with target mapping, public-signal and source capture, route selection, next-action dates, a constrained message builder, seven outreach states, live response metrics, CSV export, JSON backup, JSON import, and local-data deletion. The former $67 enrollment, Gumroad checkout, refund, launch, lifetime-access, and delivery claims were removed. Unreleased curriculum elements are explicitly labeled as a product roadmap.",
    serves: "Law students and early-career professionals who need a disciplined, evidence-producing relationship process rather than another generic networking checklist.",
    demonstrates: "Experience-to-tool translation, local-first product design, workflow modeling, outcome instrumentation, platform-aware safety, claim governance, and release-truth remediation.",
    evidence: "The canonical v2 deployment returned HTTP 200 and serves the target map, message builder, tracker, metric, export, import, and clearing logic. All executable scripts passed syntax checks; structured data parsed; IDs were unique; and legacy commerce strings were absent. RN’s outreach volumes, response rate, connections, and resulting positions remain self-reported historical evidence—not promises, causal proof, or typical outcomes. The lab does not automate LinkedIn, transmit the target list, provide career or legal advice, or guarantee any response or employment result.",
    live: "https://set-for-life-black.vercel.app/",
    source: "https://github.com/rn-collins/set-for-life",
  },
  {
    slug: "psychonaut-bookworm",
    title: "The Psychonaut Bookworm",
    category: "Publishing + research systems",
    practice: "Independent concept developed for Fat Nugs Magazine",
    status: "Live research-and-learning workbench",
    purpose: "Turn psychedelic literature into a searchable editorial research system with visible evidence state, rights-review boundaries, and reusable learning tools.",
    noticed: "A reading list preserves titles but not the reusable connections inside a body of literature: historical actors, scientific claims, quotations, geographies, primary documents, disputed interpretations, and relationships across books. It also does not tell readers which objects are full drafts, study aids, internally labeled workflow states, or excerpts awaiting rights review.",
    researched: "The v2 rebuild retained the fourteen-format collection and applied current U.S. Copyright Office guidance that fair use is contextual and has no automatic safe word count. It also reviewed current FTC guidance on clear disclosure and official NotebookLM source behavior before correcting the public truth layer.",
    built: "A searchable Research Desk spanning original editorial drafts, evidence comparisons, flashcards, and science annotations; a browser-persistent reading queue with Markdown export; per-result source counts and internal status; an evidence-and-rights ledger; rights-safe quotation and passage excerpts; and the original fourteen-format library and course tools.",
    serves: "Editors, readers, educators, publishers, researchers, and psychedelic-literature communities who need a navigable source-aware workbench.",
    demonstrates: "Editorial systems design, research UX, content atomization, knowledge organization, provenance signaling, rights-aware publishing, and durable client-side state.",
    evidence: "The live production artifact verifies 1,399 indexed editorial objects across fourteen formats, including 238 full editorial drafts, 337 quote-card objects, 563 flashcards, 112 then-versus-now comparisons, and the remaining learning and planning formats. The Research Desk exposes source-entry counts and internal editorial states, saves a local queue, and exports it. The site now states that 1,399 is an object count—not proof of external publication, peer review, licensing, independent fact-checking, or clinical authority. Third-party quotation and passage excerpts are shortened pending item-level rights review; editorial-complete and editorial-ready are internal workflow labels.",
    live: "https://psychonaut-bookworm.vercel.app/",
    source: "https://github.com/rn-collins/psychonaut-bookworm",
  },
  {
    slug: "nervous-system-studio",
    title: "Nervous System Studio",
    category: "Neuroscience + environment design",
    practice: "Independent",
    status: "Live interactive guide",
    purpose: "Help people design sensory environments and routines around calm, focus, creativity, and sleep.",
    noticed: "People often know that certain rooms, routines, sounds, lighting conditions, or levels of stimulation affect how they feel, but those observations remain anecdotal and difficult to compare. Generic wellness and décor advice also tends to prescribe a supposedly ideal environment rather than helping a person examine patterns in their own experience.",
    researched: "The experience models sensory inputs—including light, sound, scent, clutter, routine, and optional cannabis context—alongside self-reported states such as calm, focus, creativity, sleep, and overstimulation. It uses a sensory profile, repeated moment logs, cautious association language, single-variable experiments, and four environment blueprints while keeping preview data in the user's browser.",
    built: "An interactive environment-and-routine design experience translating nervous-system considerations into practical choices.",
    serves: "Individuals seeking more supportive home, work, and daily sensory environments.",
    demonstrates: "Neuroscience translation, personalized interaction design, environmental thinking, and public education.",
    evidence: "The live research preview verifies the sensory-profile flow, local-device storage design, moment logging, rules-based pattern language, four blueprint concepts, optional cannabis input, research page, privacy explanation, and safety disclaimers. Its outputs are self-reflection prompts based on user-entered associations—not diagnoses, causal findings, treatment recommendations, or proof that an environmental change improves a health condition. The displayed testimonial is explicitly a composite illustration, and the beta, wait-list, and future service claims require separate fulfillment review.",
    live: "https://nervous-system-studio.vercel.app/",
  },
  {
    slug: "psychedelic-law-library",
    title: "The Psychedelic Law Library",
    category: "Law + public knowledge infrastructure",
    practice: "Independent",
    status: "Live public library",
    purpose: "Make psychedelic law understandable across state programs, professional roles, business questions, and failure scenarios.",
    noticed: "Public discussion regularly collapses four different legal conditions—legal, decriminalized, regulated, and approved—into a single idea. In psychedelics, that confusion compounds across federal law, state programs, local reforms, professional licensure, religious-use claims, clinical research, and business operations, making it difficult for a reader to identify both the governing question and the kind of lawyer they may need.",
    researched: "The library organizes 143 plain-English articles around foundational distinctions and seven reader pathways: participants, people responding to harm, facilitators, clinicians, operators, researchers or investors, and people exploring religious use. Coverage includes Oregon and Colorado programs, federal-state conflict, licensing and scope, service-center operations, trials and biotechnology, RFRA questions, disputes, and lawyer-selection guidance, with article-specific review dates.",
    built: "A structured library of 143 plain-English articles covering Oregon and Colorado programs, facilitators, clinicians, businesses, research, and remedies.",
    serves: "Practitioners, operators, researchers, students, policymakers, and the public.",
    demonstrates: "Legal knowledge architecture, plain-language communication, issue taxonomy, and scalable public education.",
    evidence: "The live artifact verifies a searchable 143-article index, seven audience routes, article pages, review-date conventions, and a prominent legal-information boundary. This portfolio audit does not independently cite-check all articles, confirm that every page remains current, or establish an attorney-client relationship. Psychedelics law changes quickly and varies by jurisdiction and facts; users must confirm time-sensitive propositions against current statutes, regulations, agency materials, cases, and licensed counsel.",
    live: "https://law-communication-library.vercel.app/",
  },
  {
    slug: "entheogen-atlas",
    title: "Entheogen Atlas",
    category: "Psychoactive-plant science + history",
    practice: "Independent",
    status: "Controlled multidisciplinary atlas prototype · high-risk features release-blocked",
    purpose: "Map sacred plants and substances across archaeology, neuroscience, phenomenology, religious use, law, and clinical science.",
    noticed: "Psychoactive substances are commonly discussed inside a single frame—criminal law, clinical development, pharmacology, spirituality, or popular culture—even though their contemporary status emerges from interactions among all of them. Separating those histories can erase Indigenous traditions, overstate clinical certainty, or make modern prohibition appear older and more uniform than it is.",
    researched: "The atlas connects ten substances with six historical timelines and research domains spanning archaeology, receptor pharmacology, phenomenology, clinical trials, criminalization, religious exemptions, Indigenous and cultural use, global legal frameworks, decriminalization, drug interactions, and key researchers. Interactive layers include comparisons, legal-status views, an RFRA issue-spotter, risk and dose tools, a glossary, timelines, and citation-oriented reference material.",
    built: "A multidisciplinary research atlas spanning ten substances and a long historical timeline.",
    serves: "Readers, researchers, educators, journalists, and psychoactive-plant communities.",
    demonstrates: "Cross-disciplinary synthesis, research-atlas design, scientific and legal translation, and long-form public scholarship.",
    evidence: "The live artifact verifies the ten-substance structure, six timelines, multidisciplinary research sections, comparison interfaces, legal and RFRA issue-spotting tools, dose and interaction references, safety notices, and citations presented by the site. This audit does not independently validate every archaeological date, Indigenous or religious characterization, molecular or receptor claim, clinical statistic, legal status, dose range, interaction warning, editorial score, or assertion that every citation is primary. Several displays identify their own 2025 or 2026 currency limits. The atlas is educational and harm-reduction reference—not medical or legal advice—and culturally sensitive claims require engagement with the relevant peoples and authorities.",
    live: "https://entheogen-atlas.vercel.app/",
  },
  {
    slug: "cannabis-healthcare-impact-assessment",
    title: "Cannabis Healthcare Education Impact Assessment",
    category: "Cannabis education + evaluation",
    practice: "NSAG applied",
    status: "NSAG research component · unvalidated demonstration · no live collection",
    standalone: false,
    purpose: "Show how a matched pre and post design would measure whether cannabis-healthcare education changes knowledge, confidence, and intended behaviour — and make the linking mechanism inspectable before anyone builds a study on it.",
    noticed: "Cannabis-healthcare education is usually judged by attendance and by how the room felt at the end. Both are easy to collect and both answer a question nobody actually had. The questions that matter arrive later: whether a person understands disclosure and interaction risk, whether they feel able to raise cannabis use with a clinician, and whether they behave differently the next time they are in a care setting. A single survey handed out as people leave collapses all of that into one number. It also mixes together what someone already knew with what the session added, and treats a stated intention as though it were an action. Separating those requires asking the same person twice, which in turn requires linking two responses without holding a name.",
    researched: "The instrument uses a matched pre and post design with Knowledge, Attitude, and Behaviour subscales, followed by Outcome, Confidence, Motivation, Barriers, stage-of-change items, and a one-to-three-month follow-up. It collects optional demographic and care context, groups responses through event codes, normalises item scores, and sets out matched-pair, regional, legal-status, and intention-to-action analysis. Jacques et al. (2025) is identified in the public methodology as a continuing-education precedent for the format, and the page states the thresholds a data set would have to reach before publication. Every one of those choices is visible on the page rather than held in a protocol document, which is what makes the design reviewable by the people it would be run on.",
    built: "An anonymous pre/post assessment experience for education sessions, held entirely in the visitor's browser. A participant completes an intake, answers the pre items, and returns after the session for the post items; an event code groups the two responses to each other without ever holding a name. The pseudonymous linkage is the part worth looking at, because it is the part most demonstrations describe rather than show: the mechanism is visible in the running page, so a researcher can decide whether it would survive their own ethics review before anyone builds a study around it.",
    serves: "Healthcare educators running sessions for clinicians and patients, institutions that fund those sessions and want to know what they bought, participants who deserve to know what happens to their answers, and program evaluators designing the study that would come next.",
    demonstrates: "Evaluation design, behaviour-change measurement, health education, and assessment infrastructure a session facilitator could actually run in a room. The design decisions are the substance here: subscale structure, matched-pair logic, event-code grouping, and a follow-up window chosen to sit past the point where enthusiasm alone carries an answer.",
    evidence: "The live artifact demonstrates the participant intake, optional-context fields, pre and post selection, public study explanation, scoring model, follow-up concept, session-code architecture, publication thresholds, and the stated anonymity boundary. What it demonstrates is the design, not a result: the instrument is unvalidated, no sample has been collected, and the named comparison study is a precedent for the format rather than a validation of this adaptation. Any real deployment would need psychometric validation, an ethics review, and a consent process before a single response was gathered. The experience is informational and not medical advice.",
    live: "https://dru-assessment.vercel.app/",
  },
  {
    slug: "destigmatization-toolkit",
    title: "Destigmatization Toolkit for Psychoactive Plant Medicine",
    category: "Law + science + public communication",
    practice: "Organization-specific concept",
    status: "Live concept · independently initiated",
    purpose: "Give different audiences a source-grounded way to discuss psychoactive plant medicine without flattening pharmacology, law, history, or policy.",
    noticed: "Arguments about psychoactive plant medicine routinely fail because clinicians, policymakers, religious communities, lawyers, journalists, and general readers enter through different concerns and standards of proof. A single advocacy narrative can overstate clinical evidence, ignore legal exposure, erase Indigenous authority, or use language that alienates the audience before the underlying evidence is considered.",
    researched: "The toolkit organizes twenty-nine sections and 222 cited sources across stigma architecture, pharmacology, research history, substance profiles, federal and state law, implementation data, economics, safety, evidence quality, audience-specific communication, Indigenous communities, language, impermissible claims, religious use, intellectual property, access, insurance, criminal defense, practitioner compliance, business formation, tourism, youth considerations, funding, and recent RFRA litigation. Six audience paths reorder that same evidence for different starting questions.",
    built: "A 222-source reference organized into twenty-nine sections for six audiences.",
    serves: "Legal professionals, clinicians, policymakers, educators, advocates, and the public.",
    demonstrates: "Primary-source synthesis, audience-specific translation, stigma-aware communication, and large-scale reference design.",
    evidence: "The live artifact verifies a navigable twenty-nine-section reference, six audience routes, endnote area, legal and medical disclaimers, institutional and author attribution, and the presentation of 222 sources. It is independently initiated and is not represented as commissioned client work. This portfolio audit does not independently cite-check all 222 sources, validate every clinical or policy claim, confirm that every citation is primary, establish cultural authority, or treat collaboration language as endorsement by every named person or institution. Time-sensitive law and science require current primary-source and professional review.",
    live: "https://destig-toolkit.vercel.app/",
  },
  {
    slug: "evidence-studio",
    title: "Evidence·Studio",
    category: "Brand strategy + evidence governance",
    practice: "Independent",
    status: "Live practice concept",
    purpose: "Ground creator and brand strategy in evidence, disclosure, and governance for trust-sensitive markets.",
    noticed: "Creator and brand programs in regulated or credibility-sensitive markets are often optimized for attention while founder preference, weak audience assumptions, inconsistent disclosures, unsupported claims, and unclear approval rules remain untreated. Engagement metrics can then make an incoherent or risky system appear successful without showing whether it builds durable trust.",
    researched: "The practice model treats customer, market, behavioral, performance, internal, and external-research evidence as distinct inputs that must be graded for strength, recency, relevance, and directness. Its six-phase method moves from diagnosis and evidence grading through hypothesis, design, testing, and governance, with service architectures for a flagship audit, partnership strategy, operating rules, expert-led thought leadership, and continuing advisory support.",
    built: "A strategy practice surface connecting brand decisions, creator relationships, legal disclosure, and evidence standards.",
    serves: "Health, legal, wellness, and other trust-sensitive brands and creators.",
    demonstrates: "Brand-system design, evidence governance, disclosure architecture, and market-specific positioning.",
    evidence: "The live multi-page concept verifies the positioning, evidence taxonomy, six-phase method, service menu, audit and deliverable descriptions, insight library, request flow, and explicit legal-advice boundary. It does not demonstrate completed client engagements, validated conversion or trust outcomes, independently tested recommendations, or legal review of a particular campaign. FTC, platform, claims, privacy, and endorsement requirements change and must be reviewed for each engagement; the service architecture is not a substitute for counsel.",
    live: "https://creator-brand-evidence.vercel.app/",
  },
  {
    slug: "aloha-build-club",
    title: "Aloha Build Club",
    category: "Community + AI building",
    practice: "Aloha AI",
    status: "Prelaunch community and membership architecture · release-blocked",
    purpose: "Create a recurring room where people building with AI can work alongside others, get unstuck, and ship.",
    noticed: "AI lowers the cost of producing ideas and drafts but does not create the routine, social presence, next-step clarity, or accountability required to finish them. Independent builders can therefore accumulate a 'someday pile' of nearly complete work even when lack of technical skill is not the primary obstacle.",
    researched: "The membership concept combines a structured sixty-minute room, host-plus-AI unblocking, heads-down body doubling, a public moment of completion, an engagement pod, progress nudges, and a weekly shipped list. The public rationale links peer-effect, goal-accountability, cooperation, and external body-doubling evidence while explicitly distinguishing stronger presence and accountability findings from the thinner controlled evidence for body doubling itself.",
    built: "A body-doubling and build-community experience with a recurring participation model.",
    serves: "Independent builders, professionals, and people learning to make with AI.",
    demonstrates: "Community-product design, facilitation architecture, accountability systems, and accessible AI participation.",
    evidence: "The live page verifies the room format, membership and tier concepts, intended cohort cap, cited public rationale, audience boundaries, privacy language, FAQ structure, and three advertised price points. It does not verify an active cohort, scheduled daily rooms, recordings, engagement pod, shipped-list history, member outcomes, subscription processing, cancellation operations, or fulfillment of annual and Pro benefits. During inspection, enrollment calls to action appeared as buttons rather than verified checkout destinations. The cited studies support parts of the design rationale; they do not prove the club's effectiveness or guarantee productivity, shipping, income, or any other outcome.",
    live: "https://aloha-build-club.vercel.app/",
  },
  {
    slug: "regac",
    title: "REGAC — Regulatory-Education Curriculum Concept",
    category: "Legal education + compliance",
    practice: "Independent",
    status: "Public prelaunch curriculum concept · commercial and CLE release-blocked",
    purpose: "Teach cannabis and psychedelics regulatory compliance through an intensive, implementation-oriented program.",
    noticed: "Emerging-therapeutics compliance education can age quickly and often teaches rules without the institutional logic behind rulemaking, enforcement, agency comments, filing review, or federal-state conflict. Practitioners and operators need a method for returning to controlling sources and identifying what an agency is actually responding to—not merely another static overview.",
    researched: "The proposed curriculum spans state licensing, DEA scheduling and federal overlays, operator compliance, emerging therapeutics, agency decision-making, primary-source monitoring, and an AI-governance track addressing existing FTC, FDA, and state authority. Its delivery architecture combines four live sessions, recordings and summaries, a Notion hub, four source-grounded NotebookLM packs, certificate paths, Q&A, and a claimed 216-template library, with individual, firm, and institutional tiers.",
    built: "A public landing-page prototype for a proposed four-module, source-governed regulatory-education curriculum.",
    serves: "Attorneys, compliance professionals, operators, and regulated-market teams.",
    demonstrates: "Regulatory curriculum design, template systems, professional education, and compliance translation.",
    evidence: "The remediated public page verifies a prelaunch curriculum concept, four proposed learning modules, a visible development boundary, an RN authorship block, and policy routes. It does not offer enrollment, payment, a cohort, templates, course access, certificates, or CLE credit. The curriculum, source register, learning materials, ownership and confidentiality review, qualified professional review, learner terms, and delivery system remain to be completed before any commercial or credentialed launch.",
    live: "https://regac-academy.vercel.app/",
  },
  {
    slug: "narch",
    title: "NARCH — Neuroarchitecture Advisory",
    category: "Neuroscience + built environment",
    practice: "NSAG applied",
    status: "NSAG applied component · release-blocked",
    standalone: false,
    promoteLive: false,
    purpose: "Ground built-environment decisions in peer-reviewed neuroscience and auditable evidence.",
    noticed: "Architecture and planning teams often invoke wellbeing, biophilia, cognition, or healing without a traceable link between a specific design choice, a specific source, and an observable post-occupancy result. The problem is not simply access to research; it is the absence of governance infrastructure that makes a design rationale reviewable across clients, grantmakers, planning bodies, and building users.",
    researched: "NARCH applies NSAG modules M5, M7, and M10 through six assessment dimensions: evidence documentation, biophilic-design integration, acoustic and sensory governance, post-occupancy evaluation, equity and access, and grant or approval documentation. The public concept also distinguishes direct, indirect, and spatial biophilic elements; separates input-oriented certifications from measured outcomes; and proposes evidence grading and primary-source briefs as the connective tissue between research and design decisions.",
    built: "An advisory framework for translating neuroscience into client, design, and grant-facing built-environment decisions.",
    serves: "Architects, developers, institutions, designers, and funders.",
    demonstrates: "Neuroscience synthesis, built-environment governance, audit-ready evidence, and applied-practice design.",
    evidence: "The live NSAG-applied concept verifies the six-dimension framework, readiness diagnostic, signal-versus-noise guidance, glossary, hypothetical before-and-after examples, engagement architecture, and proposed Biophilic Evidence Audit. It does not verify that an audit, advisory engagement, workshop, post-occupancy evaluation, grant filing, or cited outcome has been delivered or independently validated. Claims about study volume, biological effects, percentage outcomes, standards, certifications, and source currency require source-by-source scientific and professional review before use in a project. NARCH does not establish architectural licensure, accreditation, regulatory approval, or a guarantee of health, cognitive, planning, grant, or building-performance outcomes.",
    live: "https://narch-advisory.vercel.app/",
  },
  {
    slug: "burgermeister-expansion-intel",
    title: "Burgermeister Expansion Intel",
    category: "Market expansion + regulatory intelligence",
    practice: "Organization-specific concept",
    status: "Live concept · independently initiated",
    purpose: "Track legal and regulatory signals affecting international market entry.",
    noticed: "International restaurant expansion turns a growth plan into a coordinated legal-operations problem: market entry, leases, employment, food and allergen rules, cross-border supply, trademarks, privacy, AI use, and consumer obligations arrive on different clocks and in different jurisdictions. A conventional memo can identify issues once; an operating team needs a system that preserves sources, urgency, ownership, and counsel-escalation decisions over time.",
    researched: "Using publicly available information, the concept maps an expansion scenario across the United Kingdom, European Union, United States, Germany, Poland, and possible future markets. Its 27-signal model scores impact, complexity, and urgency; distinguishes critical, high, medium, and low items; identifies issues requiring outside counsel; and connects each signal to a source library and proposed next action.",
    built: "A multi-jurisdiction expansion-intelligence interface covering the United States, United Kingdom, Germany, and Poland.",
    serves: "A restaurant group evaluating international expansion and the advisors supporting it.",
    demonstrates: "Organization-specific research, cross-border issue mapping, regulatory intelligence, and pre-proposal product design.",
    evidence: "The live prototype verifies a dashboard with 27 displayed signals, priority and jurisdiction taxonomies, outside-counsel flags, a 17-source library concept, searchable signal views, an add-signal workflow, and descriptions of optional Slack and email alerts. It is independently initiated from public information and was not commissioned, reviewed, endorsed, or adopted by Burgermeister; it does not contain or evidence access to the company's internal plans, data, counsel, or compliance program. Dates, expansion statements, revenue figures, duties, thresholds, and legal conclusions shown in the prototype require current primary-source verification and qualified local counsel before action. The scoring system is issue-spotting and prioritization—not legal advice, a complete diligence report, or proof that monitoring and alerts operate continuously.",
    live: "https://bm-intel-ivory.vercel.app/",
  },
  {
    slug: "gapi",
    title: "GAPI — AI Agent Governance Infrastructure",
    category: "AI governance + assessment",
    practice: "NSAG applied",
    status: "Framework and readiness-prototype concept · release-blocked",
    purpose: "Evaluate agent architecture through nervous-system-aware governance dimensions and make governance evidence legible to enterprise users.",
    noticed: "AI-agent assurance is frequently reduced to model capability, output accuracy, or general ethics language even though deployed conversational systems also shape attention, cognitive load, trust, choice architecture, and emotional state. Organizations need a way to document those influence mechanisms, connect them to human oversight, and monitor how they change after deployment.",
    researched: "GAPI extends NSAG modules M2 and M11 into six assessment dimensions: influence-profile documentation, cognitive-load governance, transparency and explainability, human oversight and override, demographic and population impact, and post-deployment monitoring. The concept places those dimensions alongside public signals such as the NIST AI Risk Management Framework and FTC enforcement while proposing an infrastructure-level implementation rather than a periodic policy-only review.",
    built: "A six-dimension NSAG governance assessment and certification-mark concept for AI agents.",
    serves: "AI product teams, enterprise buyers, governance leaders, and assurance functions.",
    demonstrates: "AI-agent governance, assessment design, certification architecture, and translation of institutional theory into product controls.",
    evidence: "The live NSAG-applied concept verifies the six-dimension assessment architecture, readiness diagnostic, signal-versus-noise guidance, glossary, hypothetical transformations, tiered engagement model, and proposed Agent Governance Certification mark and MCP-server direction. It does not verify a functioning governance API or MCP server, completed technical integration, customer assessment, audited model, certification decision, monitoring system, buyer acceptance, or safety outcome. The mark is a proposed NSAG program—not independent accreditation, regulatory approval, an industry standard, or a guarantee that an agent is safe, lawful, unbiased, or suitable for a particular use. Legal, scientific, security, demographic-impact, and assurance claims require domain review and empirical validation.",
    live: "https://gapi-governance.vercel.app/",
  },
  {
    slug: "womens-neuro-health",
    title: "WNH — Women’s Neuro-Health",
    category: "Women’s health + primary-source guidance",
    practice: "NSAG applied",
    status: "NSAG applied component · release-blocked",
    standalone: false,
    promoteLive: false,
    purpose: "Organize primary-source guidance around women’s neurological and nervous-system health.",
    noticed: "Women and clinicians encounter cannabis and psychedelic questions in real care contexts, but the relevant neuroscience is scattered, unevenly sex-disaggregated, and often difficult to translate across hormonal context and life stage. General-population guidance can obscure where evidence is female-specific, where it comes from animal or survey research, and where clinically useful conclusions remain uncertain.",
    researched: "WNH applies NSAG modules M3, M4, and M9 through six dimensions: sex-disaggregated evidence standards, life-stage differentiation, disclosure safety, clinician competency, psychiatric-risk communication, and patient-facing communication. The public evidence library demonstrates an intended method of annotating primary sources by study type, finding, limitation, and evidence grade rather than presenting all citations as equally conclusive.",
    built: "A public guidance experience connecting evidence, life-stage context, and practical next questions.",
    serves: "Women, caregivers, clinicians, educators, and health-system stakeholders.",
    demonstrates: "Women’s-health evidence synthesis, audience-sensitive communication, and public guidance design.",
    evidence: "The live NSAG-applied concept verifies the six-dimension framework, four-volume guide-series proposal, annotated evidence examples, readiness diagnostic, signal-versus-noise section, glossary, hypothetical examples, and engagement interface. It does not establish that the paid guides are complete, clinically reviewed, purchasable, delivered, or used in care; that the evidence library is exhaustive or continuously current; or that any intervention is safe or effective for an individual. Some displayed sources are animal, small-sample, survey, or early-stage evidence and cannot support universal dosing, treatment, risk, or life-stage conclusions. WNH is educational, not medical advice, diagnosis, informed consent, patient-specific decision support, or a substitute for qualified clinical care and current source review.",
    live: "https://wnh-guide.vercel.app/",
  },
  {
    slug: "sport-nsag",
    title: "SPORT — Nervous-System-Aware Athletic Governance",
    category: "Sport + institutional governance",
    practice: "NSAG applied",
    status: "Public applied-framework concept · assessment and commercial release blocked",
    purpose: "Apply Nervous-System-Aware Governance to athletic institutions and athlete welfare.",
    noticed: "Sports organizations govern athlete nervous-system inputs through schedules, travel, training and recovery expectations, facilities, organizational culture, media obligations, and career transitions, yet those decisions are usually separated across coaching, operations, welfare, and communications. That fragmentation can hide cumulative load and make performance or wellbeing effects difficult to document as institutional outputs.",
    researched: "SPORT applies NSAG modules M5, M8, and M15 through six assessment dimensions: physical environment; schedule and recovery; travel and logistical stress; psychological safety and culture; media and public-facing stress; and development and career transition. The public framework distinguishes adaptive from impairing stress, places developmental stage and athlete agency inside governance, and proposes source-backed policies and outcome measures instead of treating awareness or wearable data as sufficient evidence.",
    built: "A six-dimension governance system spanning load, recovery, scheduling, travel, cognitive performance, psychological environments, and organizational culture.",
    serves: "Athletic organizations, teams, governing bodies, coaches, and athlete-welfare leaders.",
    demonstrates: "Framework extension, sport governance, welfare-system design, and institution-level assessment.",
    evidence: "The live NSAG-applied concept verifies the six-dimension framework, five-question readiness diagnostic, signal-versus-noise guidance, glossary, hypothetical before-and-after examples, proposed Athlete's Nervous System Audit, ninety-day roadmap, and tiered engagement architecture. It does not verify an assessment, team or league engagement, client pipeline, completed audit, roadmap implementation, improved performance, reduced injury, athlete-welfare outcome, or institutional adoption. References to F1, LA28, NCAA materials, study findings, risk percentages, and evidence currency require direct source verification and should not imply affiliation, access, endorsement, or a validated causal effect. SPORT is an institutional-design and assessment concept—not medical care, coaching, legal advice, accreditation, or a guarantee of health or competitive outcomes.",
    live: "https://sport-nsag.vercel.app/",
  },
  {
    slug: "inflection-radar",
    title: "Inflection Radar",
    category: "Growth intelligence + governed research",
    practice: "Organization-specific concept",
    status: "Live decision room · independently initiated proposal",
    purpose: "Help a health-communications organization identify emerging neuropsychiatry opportunities before they become ordinary pursuits while preserving source rights, confidence, contradictions, and human authority.",
    noticed: "Real Chemistry publicly evidenced substantial analytics, communications, access, media, and growth capabilities, but its public materials did not establish the exact upstream workflow used to identify and govern prospective-account signals. That was treated as an internally unknown question—not as proof that no such capability exists.",
    researched: "The proposal used permitted public sources to map Real Chemistry's visible capabilities, the neuropsychiatry opportunity environment, source-permission constraints, evidence tiers, human review gates, and the operating decisions required for an eight-week pilot.",
    built: "An independently initiated proposal package: a role-aware interactive decision room, illustrative score, source-permission explorer, proposed eight-week execution model, executive brief, report, and meeting deck.",
    serves: "Growth, strategy, analytics, business-development, legal, privacy, and executive reviewers evaluating whether to authorize a governed public-source pilot.",
    demonstrates: "Public-source organizational diligence, opportunity sensing, evidence and rights governance, human-reviewed scoring, proposal architecture, executive communication, and the conversion of research into a decision-ready interactive system.",
    evidence: "The system is a public-source proposal prepared independently for discussion with Real Chemistry. It is not commissioned work, a representation of Real Chemistry's internal systems, or a statement that publicly unverified capabilities do not exist. It excludes internal, client-confidential, patient-level, licensed-restricted, and other nonpublic information.",
    live: "https://inflection-radar-real-chemistry.vercel.app/",
    source: "https://github.com/rn-collins/inflection-radar-real-chemistry",
    artifacts: [
      { label: "Read executive brief", href: "https://inflection-radar-real-chemistry.vercel.app/assets/executive-brief.pdf" },
      { label: "Read full report", href: "https://inflection-radar-real-chemistry.vercel.app/assets/full-report.pdf" },
      { label: "Open meeting deck", href: "https://inflection-radar-real-chemistry.vercel.app/assets/meeting-deck.pptx" },
    ],
  },
  {
    slug: "creator-rights-framework",
    title: "Creator Rights Issue Spotter",
    category: "Creator economy + governance",
    practice: "Aloha AI",
    status: "Live browser-local educational issue spotter",
    purpose: "Put rights, disclosure, compensation, data, and AI-use questions in front of creator activation decisions.",
    noticed: "Creator activations can combine human or synthetic personas, AI-generated content, likeness rights, music provenance, sponsorship disclosures, multiple platform policies, and cross-border rules within one campaign. Standard influencer checklists and pre-generative-AI agreements may therefore miss who authorized what, which disclosure applies in each format, and when specialist review is required before activation.",
    researched: "The diagnostic organizes seven issue-spotting gates around creator type, AI-contract language, written authorization for likeness use, format-specific FTC disclosure, music licensing and provenance, European-market exposure, and platform-specific AI labeling. Its response logic converts answers into a pre-activation remediation list and escalates selected issues to legal review rather than averaging them into a generic risk score.",
    built: "A seven-question browser-local educational issue spotter covering creator type, AI terms, likeness or voice use, disclosures, music, EU exposure, and platform-policy review.",
    serves: "Creators, brands, agencies, legal teams, and partnership leaders.",
    demonstrates: "Creator-rights issue spotting, governance-by-design, legal research, and practical decision-tool construction.",
    evidence: "The remediated live tool verifies seven question paths, conditional issue prompts, a no-clearance result boundary, restart control, related links, a no-data LinkedIn contact path, visible RN authorship, and privacy, terms, robots, and sitemap routes. The former automated regulatory-feed presentation is suppressed. The tool does not inspect documents or establish ownership, consent, disclosure adequacy, substantiation, platform approval, rights clearance, legal compliance, or permission to publish; current matter-specific review remains required.",
    live: "https://aloha-creator-rights.vercel.app/",
  },
];

export function getPublicBuild(slug: string) {
  return publicBuilds.find((build) => build.slug === slug);
}
