export type PublicBuild = {
  slug: string;
  title: string;
  category: string;
  practice: string;
  status: string;
  purpose: string;
  built: string;
  serves: string;
  demonstrates: string;
  live: string;
  source?: string;
  noticed?: string;
  researched?: string;
  evidence?: string;
  artifacts?: { label: string; href: string }[];
};

export const publicBuilds: PublicBuild[] = [
  {
    slug: "aloha-ai",
    title: "Aloha AI",
    category: "AI strategy + implementation",
    practice: "Aloha AI",
    status: "Live practice platform · active development",
    purpose: "Help organizations find where AI belongs, what should remain human, and how a useful implementation can be governed and maintained.",
    built: "A client-facing strategy and delivery platform spanning decision tools, workflow diagnostics, implementation planning, source-backed resources, clinics, and learning experiences.",
    serves: "Organizations and teams deciding whether, where, and how to implement AI responsibly.",
    demonstrates: "Product architecture, evidence-grounded AI strategy, service design, implementation planning, and the ability to turn advisory work into usable infrastructure.",
    live: "https://aloha-ai-consulting.vercel.app/",
    source: "https://github.com/rn-collins/aloha-ai-consulting",
  },
  {
    slug: "sovereign-stack",
    title: "The Sovereign Stack",
    category: "AI governance + community authority",
    practice: "Aloha AI",
    status: "Live working concept",
    purpose: "Carry community authority through every layer of an AI system—from purpose and data to models, use, review, and refusal.",
    noticed: "Purple Maiʻa's public work described a technical stack involving local compute, open models, edge hardware, place-based environmental observation, and Indigenous approaches to technology. The design question was whether authority, knowledge boundaries, accountability, withdrawal, and refusal could travel through that technical body in a durable form.",
    researched: "The proposal was grounded in Purple Maiʻa's public descriptions of the Sovereign Stack, KILO, Kānāwai, Kula, Waiw.AI, and Rooted Futures, then organized around the unresolved governance questions a community-authorized process would still have to answer.",
    built: "A governance and learning layer that makes ownership, authority, data, model choice, review, exit, and refusal visible as design decisions rather than afterthoughts.",
    serves: "Communities and institutions evaluating AI systems on their own terms.",
    demonstrates: "Sociotechnical systems thinking, governance architecture, public explanation, and interactive proposal design.",
    evidence: "This is an independently prepared working proposal for discussion with Purple Maiʻa. It is not a Purple Maiʻa product, policy, endorsement, approved protocol, community consent, or community-authorized framework. Purple Maiʻa and relevant community and cultural authorities—not RN—would define the substantive values, standing, knowledge permissions, and approvals.",
    live: "https://sovereign-stack-psi.vercel.app/",
  },
  {
    slug: "ai-build-budget-calculator",
    title: "AI Build Budget Calculator",
    category: "Business + decision tools",
    practice: "Aloha AI",
    status: "Live calculator",
    purpose: "Make the labor, fees, phases, and taxes behind a professional AI build legible before work begins.",
    noticed: "Custom AI projects are often discussed as a single price even though discovery, research, architecture, implementation, testing, documentation, launch, and maintenance require different kinds and amounts of labor. That opacity makes early scoping difficult for both a buyer and a builder.",
    researched: "The calculator models professional-services cost from editable hourly rates, low/high labor estimates, phase structure, self-employment and general-excise-tax settings, and common build presets. Its research object is delivery architecture and transparent estimation rather than a universal market-price claim.",
    built: "An interactive planning calculator that estimates professional-service hours and costs by build phase.",
    serves: "Founders, consultants, and organizations scoping an AI implementation.",
    demonstrates: "Commercial modeling, transparent scoping, interaction design, and translation of delivery work into a practical decision tool.",
    evidence: "The live tool produces configurable planning estimates and can export the working model as CSV. Its figures are not quotes, guarantees, financial advice, or independently validated market benchmarks; actual scope, tax treatment, staffing, vendor costs, and delivery conditions require project-specific review.",
    live: "https://ai-budget-calc-red.vercel.app/",
  },
  {
    slug: "source-integrity-audit",
    title: "Source Integrity Audit",
    category: "Evidence + legal operations",
    practice: "Independent",
    status: "Live service system",
    purpose: "Verify citations and source support before a publisher publishes or a legal team files.",
    noticed: "AI-assisted documents can contain authorities that do not exist, sources that do not support the attributed proposition, outdated law or science, vague attribution, and claims whose confidence exceeds the underlying evidence. A spot check cannot show which claims were actually reviewed.",
    researched: "The service architecture distinguishes express and implied claims, grades verifiability, prioritizes primary sources, checks date and currency, evaluates attribution, records funding or conflicts, assigns confidence, and produces an evidence-grade summary. The public experience also exposes a limited quick-check tool and the EVIDENCE framework.",
    built: "A documented verification service and public intake surface for checking whether cited authorities exist, are current, and support the proposition attributed to them.",
    serves: "Publishers, law firms, researchers, and trust-sensitive organizations.",
    demonstrates: "Citation verification, evidence provenance, legal-research discipline, and productized quality assurance.",
    evidence: "This portfolio record verifies the public service design, methodology explanation, quick-check interface, deliverables, and stated turnaround structure. It does not independently validate every historical example, performance claim, price, or claimed prior audit result on the underlying commercial page. The service is informational and does not replace filing counsel, editorial judgment, or domain-specific professional review.",
    live: "https://provenance-verify.vercel.app/",
  },
  {
    slug: "one-person-firm-os",
    title: "One-Person-Firm OS",
    category: "Independent work + operating systems",
    practice: "Institutions of One",
    status: "Live operating system",
    purpose: "Give solo consultants and fractional executives the operating infrastructure required to run a practice.",
    noticed: "Independent professionals often accumulate disconnected notes, task managers, client records, AI conversations, and automations. The tools exist, but the work of deciding what belongs where, what should happen next, and how the system stays current remains with the operator.",
    researched: "The operating model organizes a solo practice around a Notion command center, client and revenue tracking, task routing, brand-specific Claude projects and skills, three defined AI-agent roles, a weekly review, guided handoff, and post-implementation check-in.",
    built: "A one-week practice setup system organizing positioning, offers, delivery, administration, evidence, and client operations.",
    serves: "Solo consultants, fractional executives, and independent professionals.",
    demonstrates: "Operational product design, independent-work infrastructure, process architecture, and packaged implementation.",
    evidence: "The live page documents a service architecture and three proposed delivery tiers. Statements about RN's own brand, client, workload, assistant, and daily-system usage are self-reported operating context, not independently audited performance evidence. Purchasing and delivery workflows on the underlying site require their own commercial, privacy, and fulfillment review.",
    live: "https://opfos-firm.vercel.app/",
  },
  {
    slug: "ai-for-developing-brains",
    title: "AI for Developing Brains",
    category: "Education + neurotechnology",
    practice: "NSAG · M12",
    status: "Live workshop experience",
    purpose: "Explain how children’s developing brains interact with AI without panic, hype, or unsupported certainty.",
    noticed: "Families and schools are being asked to make decisions about child-facing AI while public discussion often collapses into either technological optimism or generalized harm claims. The missing layer is an age- and context-sensitive way to connect what a child is doing with AI to the developing cognitive and physiological systems involved.",
    researched: "The public experience organizes developmental questions around age stage, early-environment stability, caregiver-child interaction, milestone surveillance, institutional and technology-setting design, adversity buffering, and vendor or sponsorship governance. It situates the workshop within NSAG M12 and related nervous-system-aware governance modules.",
    built: "A primary-source-grounded, ninety-minute parent and educator workshop connecting developmental neuroscience, AI use, practical boundaries, and family decision-making.",
    serves: "Parents, caregivers, educators, schools, and youth-serving organizations.",
    demonstrates: "Developmental-neuroscience translation, curriculum design, risk communication, and nervous-system-aware education.",
    evidence: "The live site presents a workshop, guide, assessment dimensions, self-assessment, pricing, and booking or wait-list interfaces. This portfolio record verifies that public product architecture; it does not independently certify every neuroscience claim, citation, outcome promise, availability statement, or fulfillment pathway. The material is educational and not medical advice.",
    live: "https://kids-developing-brains.vercel.app/",
  },
  {
    slug: "transform-drug-market-transition-observatory",
    title: "Transform Drug Market Transition Observatory",
    category: "Drug policy + monitoring",
    practice: "Independent research",
    status: "Live observatory",
    purpose: "Monitor whether drug-market transitions find a workable regulatory balance.",
    built: "A monitoring observatory organized around Transform Drug Policy Foundation frameworks and the legal, market, public-health, and governance signals that shape transition outcomes.",
    serves: "Drug-policy researchers, regulators, advocates, and institutions evaluating market transitions.",
    demonstrates: "Framework operationalization, longitudinal monitoring, policy synthesis, and public intelligence design.",
    live: "https://transform-observatory.vercel.app/",
  },
  {
    slug: "zero-to-frontier",
    title: "Zero → Frontier",
    category: "AI education + public resources",
    practice: "Aloha AI",
    status: "Live public guide",
    purpose: "Make the history, concepts, and present frontier of AI understandable through a fully sourced learning path.",
    built: "A free guide moving from Turing’s 1950 thought experiment to frontier models, supported by a library of 237 free resources.",
    serves: "Curious adults, students, professionals, and teams seeking a structured introduction to AI.",
    demonstrates: "Curriculum architecture, technical translation, source curation, and accessible public education.",
    live: "https://zero-to-frontier.vercel.app/",
    source: "https://github.com/rn-collins/zero-to-frontier",
  },
  {
    slug: "psych-ops-directory",
    title: "Psych Ops Directory",
    category: "Psychedelic operations + ecosystem infrastructure",
    practice: "Independent",
    status: "Live directory",
    purpose: "Make the operational infrastructure of the psychedelic ecosystem searchable across legal, financial, clinical, and support functions.",
    built: "A curated directory of vendors and organizations across twenty-two operational categories.",
    serves: "Psychedelic organizations, operators, researchers, clinicians, and professional-service providers.",
    demonstrates: "Ecosystem taxonomy, directory architecture, field research, and operational knowledge design.",
    live: "https://psych-ops-directory.vercel.app/",
  },
  {
    slug: "set-for-life",
    title: "Set for Life",
    category: "Legal education + career systems",
    practice: "Independent",
    status: "Live self-serve course",
    purpose: "Turn relationship-building and LinkedIn outreach into a repeatable networking system for law students.",
    built: "A self-serve course grounded in RN’s 1L networking process, outreach data, and resulting opportunities.",
    serves: "Law students who need a practical relationship-building system beyond job-board applications.",
    demonstrates: "Experience-to-curriculum translation, career-system design, evidence-backed instruction, and productization.",
    live: "https://set-for-life-black.vercel.app/",
  },
  {
    slug: "psychonaut-bookworm",
    title: "The Psychonaut Bookworm",
    category: "Publishing + media systems",
    practice: "Fat Nugs Magazine concept",
    status: "Live media-library concept",
    purpose: "Turn psychedelic literature into a structured, reusable media and editorial system.",
    built: "A media library presenting 1,399 planned or finished-format pieces across fourteen content types tied to psychedelic literature.",
    serves: "Editors, readers, educators, publishers, and psychedelic-literature communities.",
    demonstrates: "Editorial systems design, content atomization, knowledge organization, and scalable media planning.",
    live: "https://psychonaut-bookworm.vercel.app/",
  },
  {
    slug: "startup-legal-risk-monitor",
    title: "Startup Legal Risk Monitor",
    category: "Legal intelligence + monitoring",
    practice: "Aloha AI",
    status: "Live controlled prototype · noindex",
    purpose: "Track regulatory signals that can alter a startup’s legal and operating risk.",
    built: "A monitoring interface covering SEC filings, FTC enforcement, CFPB guidance, and AI legislation with alert-oriented presentation.",
    serves: "Founders, startup counsel, compliance teams, and investors.",
    demonstrates: "Regulatory monitoring, legal taxonomy, risk communication, and decision-support design.",
    live: "https://legal-risk-monitor.vercel.app/",
  },
  {
    slug: "nervous-system-studio",
    title: "Nervous System Studio",
    category: "Neuroscience + environment design",
    practice: "Independent",
    status: "Live interactive guide",
    purpose: "Help people design sensory environments and routines around calm, focus, creativity, and sleep.",
    built: "An interactive environment-and-routine design experience translating nervous-system considerations into practical choices.",
    serves: "Individuals seeking more supportive home, work, and daily sensory environments.",
    demonstrates: "Neuroscience translation, personalized interaction design, environmental thinking, and public education.",
    live: "https://nervous-system-studio.vercel.app/",
  },
  {
    slug: "psychedelic-law-library",
    title: "The Psychedelic Law Library",
    category: "Law + public knowledge infrastructure",
    practice: "Independent",
    status: "Live public library",
    purpose: "Make psychedelic law understandable across state programs, professional roles, business questions, and failure scenarios.",
    built: "A structured library of 143 plain-English articles covering Oregon and Colorado programs, facilitators, clinicians, businesses, research, and remedies.",
    serves: "Practitioners, operators, researchers, students, policymakers, and the public.",
    demonstrates: "Legal knowledge architecture, plain-language communication, issue taxonomy, and scalable public education.",
    live: "https://law-communication-library.vercel.app/",
  },
  {
    slug: "eolpc-knowledge-system",
    title: "EOLPC Knowledge System",
    category: "Clinical evidence + AI retrieval",
    practice: "Independent",
    status: "Live controlled prototype · noindex",
    purpose: "Retrieve current primary sources for psychedelic end-of-life care questions.",
    built: "An AI-assisted knowledge interface connected to live PubMed and ClinicalTrials.gov source pathways.",
    serves: "Researchers, clinicians, educators, and teams studying psychedelic end-of-life care.",
    demonstrates: "Clinical evidence retrieval, source grounding, sensitive-domain interface design, and knowledge-system prototyping.",
    live: "https://eolpc-demo.vercel.app/",
  },
  {
    slug: "entheogen-atlas",
    title: "Entheogen Atlas",
    category: "Psychoactive-plant science + history",
    practice: "Independent",
    status: "Live research atlas",
    purpose: "Map sacred plants and substances across archaeology, neuroscience, phenomenology, religious use, law, and clinical science.",
    built: "A multidisciplinary research atlas spanning ten substances and a long historical timeline.",
    serves: "Readers, researchers, educators, journalists, and psychoactive-plant communities.",
    demonstrates: "Cross-disciplinary synthesis, research-atlas design, scientific and legal translation, and long-form public scholarship.",
    live: "https://entheogen-atlas.vercel.app/",
  },
  {
    slug: "cannabis-healthcare-impact-assessment",
    title: "Cannabis Healthcare Education Impact Assessment",
    category: "Cannabis education + evaluation",
    practice: "NSAG applied",
    status: "Live assessment",
    purpose: "Measure whether cannabis-healthcare education changes knowledge, confidence, or intended behavior.",
    built: "An anonymous pre/post assessment experience for education sessions.",
    serves: "Healthcare educators, institutions, participants, and program evaluators.",
    demonstrates: "Evaluation design, behavior-change measurement, health education, and usable assessment infrastructure.",
    live: "https://dru-assessment.vercel.app/",
  },
  {
    slug: "destigmatization-toolkit",
    title: "Destigmatization Toolkit for Psychoactive Plant Medicine",
    category: "Law + science + public communication",
    practice: "Organization-specific concept",
    status: "Live concept · independently initiated",
    purpose: "Give different audiences a source-grounded way to discuss psychoactive plant medicine without flattening pharmacology, law, history, or policy.",
    built: "A 222-source reference organized into twenty-nine sections for six audiences.",
    serves: "Legal professionals, clinicians, policymakers, educators, advocates, and the public.",
    demonstrates: "Primary-source synthesis, audience-specific translation, stigma-aware communication, and large-scale reference design.",
    live: "https://destig-toolkit.vercel.app/",
  },
  {
    slug: "evidence-studio",
    title: "Evidence·Studio",
    category: "Brand strategy + evidence governance",
    practice: "Independent",
    status: "Live practice concept",
    purpose: "Ground creator and brand strategy in evidence, disclosure, and governance for trust-sensitive markets.",
    built: "A strategy practice surface connecting brand decisions, creator relationships, legal disclosure, and evidence standards.",
    serves: "Health, legal, wellness, and other trust-sensitive brands and creators.",
    demonstrates: "Brand-system design, evidence governance, disclosure architecture, and market-specific positioning.",
    live: "https://creator-brand-evidence.vercel.app/",
  },
  {
    slug: "aloha-build-club",
    title: "Aloha Build Club",
    category: "Community + AI building",
    practice: "Aloha AI",
    status: "Live community concept",
    purpose: "Create a recurring room where people building with AI can work alongside others, get unstuck, and ship.",
    built: "A body-doubling and build-community experience with a recurring participation model.",
    serves: "Independent builders, professionals, and people learning to make with AI.",
    demonstrates: "Community-product design, facilitation architecture, accountability systems, and accessible AI participation.",
    live: "https://aloha-build-club.vercel.app/",
  },
  {
    slug: "regac",
    title: "REGAC — Regulatory Compliance Intensive",
    category: "Legal education + compliance",
    practice: "Independent",
    status: "Live four-week program · CLE pending",
    purpose: "Teach cannabis and psychedelics regulatory compliance through an intensive, implementation-oriented program.",
    built: "A four-week program supported by 216 attorney-grade templates and a professional-education pathway.",
    serves: "Attorneys, compliance professionals, operators, and regulated-market teams.",
    demonstrates: "Regulatory curriculum design, template systems, professional education, and compliance translation.",
    live: "https://regac-academy.vercel.app/",
  },
  {
    slug: "narch",
    title: "NARCH — Neuroarchitecture Advisory",
    category: "Neuroscience + built environment",
    practice: "NSAG applied",
    status: "Live applied-practice concept",
    purpose: "Ground built-environment decisions in peer-reviewed neuroscience and auditable evidence.",
    built: "An advisory framework for translating neuroscience into client, design, and grant-facing built-environment decisions.",
    serves: "Architects, developers, institutions, designers, and funders.",
    demonstrates: "Neuroscience synthesis, built-environment governance, audit-ready evidence, and applied-practice design.",
    live: "https://narch-advisory.vercel.app/",
  },
  {
    slug: "burgermeister-expansion-intel",
    title: "Burgermeister Expansion Intel",
    category: "Market expansion + regulatory intelligence",
    practice: "Organization-specific concept",
    status: "Live concept · independently initiated",
    purpose: "Track legal and regulatory signals affecting international market entry.",
    built: "A multi-jurisdiction expansion-intelligence interface covering the United States, United Kingdom, Germany, and Poland.",
    serves: "A restaurant group evaluating international expansion and the advisors supporting it.",
    demonstrates: "Organization-specific research, cross-border issue mapping, regulatory intelligence, and pre-proposal product design.",
    live: "https://bm-intel-ivory.vercel.app/",
  },
  {
    slug: "psych-ops-intel",
    title: "Psych Ops Intel",
    category: "Psychedelic regulation + monitoring",
    practice: "Independent",
    status: "Live regulatory monitor",
    purpose: "Surface primary-source psilocybin regulatory updates across active state systems.",
    built: "An automated weekly sweep of Oregon, Colorado, Nevada, New Mexico, and related primary-source agencies.",
    serves: "Psychedelic operators, attorneys, researchers, educators, and policy teams.",
    demonstrates: "Primary-source monitoring, regulatory taxonomy, update automation, and field-intelligence delivery.",
    live: "https://psychops-intel.vercel.app/",
  },
  {
    slug: "gapi",
    title: "GAPI — AI Agent Governance Infrastructure",
    category: "AI governance + assessment",
    practice: "NSAG applied",
    status: "Live applied assessment",
    purpose: "Evaluate agent architecture through nervous-system-aware governance dimensions and make governance evidence legible to enterprise users.",
    built: "A six-dimension NSAG governance assessment and certification-mark concept for AI agents.",
    serves: "AI product teams, enterprise buyers, governance leaders, and assurance functions.",
    demonstrates: "AI-agent governance, assessment design, certification architecture, and translation of institutional theory into product controls.",
    live: "https://gapi-governance.vercel.app/",
  },
  {
    slug: "womens-neuro-health",
    title: "WNH — Women’s Neuro-Health",
    category: "Women’s health + primary-source guidance",
    practice: "NSAG applied",
    status: "Live guidance system",
    purpose: "Organize primary-source guidance around women’s neurological and nervous-system health.",
    built: "A public guidance experience connecting evidence, life-stage context, and practical next questions.",
    serves: "Women, caregivers, clinicians, educators, and health-system stakeholders.",
    demonstrates: "Women’s-health evidence synthesis, audience-sensitive communication, and public guidance design.",
    live: "https://wnh-guide.vercel.app/",
  },
  {
    slug: "sport-nsag",
    title: "SPORT — Nervous-System-Aware Athletic Governance",
    category: "Sport + institutional governance",
    practice: "NSAG applied",
    status: "Live applied framework",
    purpose: "Apply Nervous-System-Aware Governance to athletic institutions and athlete welfare.",
    built: "A six-dimension governance system spanning load, recovery, scheduling, travel, cognitive performance, psychological environments, and organizational culture.",
    serves: "Athletic organizations, teams, governing bodies, coaches, and athlete-welfare leaders.",
    demonstrates: "Framework extension, sport governance, welfare-system design, and institution-level assessment.",
    live: "https://sport-nsag.vercel.app/",
  },
  {
    slug: "inflection-radar",
    title: "Inflection Radar",
    category: "Growth intelligence + governed research",
    practice: "Organization-specific concept",
    status: "Live decision room · independently initiated proposal",
    purpose: "Help a health-communications organization identify emerging neuropsychiatry opportunities before they become ordinary pursuits while preserving source rights, confidence, contradictions, and human authority.",
    noticed: "Real Chemistry publicly evidenced substantial analytics, communications, access, media, and growth capabilities, but its public materials did not establish the exact upstream workflow used to identify and govern prospective-account signals. That was treated as an internally unknown question—not as proof that no such capability exists.",
    researched: "The proposal used permitted public sources to map Real Chemistry's visible capabilities, the neuropsychiatry opportunity environment, source-permission constraints, evidence tiers, human review gates, and the operating decisions required for an eight-week pilot.",
    built: "A role-aware interactive decision room with four reading paths; a tunable sample account score; claim-level evidence distinctions; a source-permission explorer; an eight-week execution model; an executive brief; a full internal report; and a meeting deck.",
    serves: "Growth, strategy, analytics, business-development, legal, privacy, and executive reviewers evaluating whether to authorize a governed public-source pilot.",
    demonstrates: "Public-source organizational diligence, opportunity sensing, evidence and rights governance, human-reviewed scoring, proposal architecture, executive communication, and the conversion of research into a decision-ready interactive system.",
    evidence: "The system is a public-source proposal prepared independently for discussion with Real Chemistry. It is not commissioned work, a representation of Real Chemistry's internal systems, or a statement that publicly unverified capabilities do not exist. It excludes internal, client-confidential, patient-level, licensed-restricted, and other nonpublic information.",
    live: "https://inflection-radar-real-chemistry.vercel.app/",
    source: "https://github.com/rn-collins/inflection-radar-real-chemistry",
    artifacts: [
      { label: "Read executive brief", href: "https://inflection-radar-real-chemistry.vercel.app/assets/executive-brief.pdf" },
      { label: "Read full report", href: "https://inflection-radar-real-chemistry.vercel.app/assets/full-report.pdf" },
      { label: "Open meeting deck", href: "https://inflection-radar-real-chemistry.vercel.app/assets/meeting-deck.pptx" },
    ],
  },
  {
    slug: "creator-rights-framework",
    title: "Creator Rights Framework",
    category: "Creator economy + governance",
    practice: "Aloha AI",
    status: "Live governance tool",
    purpose: "Put rights, disclosure, compensation, data, and AI-use questions in front of creator activation decisions.",
    built: "A seven-question governance check cross-referenced with FTC enforcement and emerging AI-law considerations.",
    serves: "Creators, brands, agencies, legal teams, and partnership leaders.",
    demonstrates: "Creator-rights issue spotting, governance-by-design, legal research, and practical decision-tool construction.",
    live: "https://aloha-creator-rights.vercel.app/",
  },
];

export function getPublicBuild(slug: string) {
  return publicBuilds.find((build) => build.slug === slug);
}
