export type PublicBuild = {
  slug: string;
  title: string;
  category: string;
  practice: string;
  status: string;
  purpose: string;
  built: string;
  serves: string;
  demonstrates: string;
  live: string;
  /** False when this is evidence nested under a parent practice, not a standalone portfolio count. */
  standalone?: boolean;
  /** False when the audited artifact should not be promoted until its release gates are cleared. */
  promoteLive?: boolean;
  source?: string;
  noticed?: string;
  researched?: string;
  evidence?: string;
  artifacts?: { label: string; href: string }[];
};

export const publicBuilds: PublicBuild[] = [
  {
    slug: "aloha-ai",
    title: "Aloha AI",
    category: "AI strategy + implementation",
    practice: "Aloha AI",
    status: "Live practice platform · active development",
    purpose: "Help organizations find where AI belongs, what should remain human, and how a useful implementation can be governed and maintained.",
    noticed: "Organizations are often pushed from a vague desire to 'use AI' directly into vendor selection or deployment. The missing work is decision architecture: defining the bounded problem, considering non-AI alternatives, identifying affected people, preserving evidence and uncertainty, assigning ownership, and deciding in advance when a pilot should stop or roll back.",
    researched: "Aloha AI organizes that problem through a claim-source-limit-review evidence standard and a path from the actual decision to operating conditions and a preserved decision record. Its current public tool set operationalizes workflow scoping, alternatives and evidence review, vendor comparison, pilot design, ownership, affected-party input, stop conditions, rollback, and scheduled reconsideration rather than treating adoption as a one-time technology purchase.",
    built: "A client-facing strategy and delivery platform spanning decision tools, workflow diagnostics, implementation planning, source-backed resources, clinics, and learning experiences.",
    serves: "Organizations and teams deciding whether, where, and how to implement AI responsibly.",
    demonstrates: "Product architecture, evidence-grounded AI strategy, service design, implementation planning, and the ability to turn advisory work into usable infrastructure.",
    evidence: "The live platform verifies a routed starting experience; open learning and Source Desk surfaces; service, policy, accessibility, procurement, and sponsorship pathways; and four complete browser-local v1 tools: Opportunity Studio, Decision Record Builder, Tool & Vendor Comparison Builder, and Pilot Design Kit. The tools expose guided prompts, rule-based logic or controlling gates, local persistence, readable results, portable Markdown or JSON output where promised, reset controls, and explicit limits without requiring an account or transmitting entries to Aloha AI. This does not establish completed client engagements, verified source accuracy, enterprise collaboration or synchronization, professional advice, compliance certification, authorization to deploy, or improved organizational outcomes. Aloha AI remains the developing client-facing strategy and build practice; it is distinct from NSAG, although it may build technical infrastructure that implements NSAG work.",
    live: "https://aloha-ai-consulting.vercel.app/",
    source: "https://github.com/rn-collins/aloha-ai-consulting",
  },
  {
    slug: "sovereign-stack",
    title: "Sovereign Stack governance-layer concept",
    category: "AI governance + community authority",
    practice: "Aloha AI",
    status: "Browser-local proposal prototype · independently initiated · release-blocked",
    purpose: "Carry community authority through every layer of an AI system—from purpose and data to models, use, review, and refusal.",
    noticed: "Purple Maiʻa's public work described a technical stack involving local compute, open models, edge hardware, place-based environmental observation, and Indigenous approaches to technology. The design question was whether authority, knowledge boundaries, accountability, withdrawal, and refusal could travel through that technical body in a durable form.",
    researched: "The proposal was grounded in Purple Maiʻa's public descriptions of the Sovereign Stack, KILO, Kānāwai, Kula, Waiw.AI, and Rooted Futures, then organized around the unresolved governance questions a community-authorized process would still have to answer.",
    built: "A governance and learning layer that makes ownership, authority, data, model choice, review, exit, and refusal visible as design decisions rather than afterthoughts.",
    serves: "Communities and institutions evaluating AI systems on their own terms.",
    demonstrates: "Sociotechnical systems thinking, governance architecture, public explanation, and interactive proposal design.",
    evidence: "This is an independently prepared working proposal for discussion with Purple Maiʻa. It is not a Purple Maiʻa product, policy, endorsement, approved protocol, community consent, or community-authorized framework. Purple Maiʻa and relevant community and cultural authorities—not RN—would define the substantive values, standing, knowledge permissions, and approvals.",
    live: "https://sovereign-stack-psi.vercel.app/",
  },
  {
    slug: "ai-build-budget-calculator",
    title: "AI Build Labor Scenario Calculator",
    category: "Business planning + estimation prototype",
    practice: "Aloha AI",
    status: "Live editable labor-scenario calculator · remediated August 2026",
    purpose: "Make an editable professional-services labor scenario visible by phase before project-specific discovery and quotation.",
    noticed: "Custom AI projects are often discussed as a single price even though discovery, research, architecture, implementation, testing, documentation, launch, and maintenance require different kinds and amounts of labor. That opacity makes early scoping difficult for both a buyer and a builder.",
    researched: "The prototype organizes common delivery phases and configurable low/high hours. Defaults are authored planning assumptions, not validated market benchmarks. Tax, vendor, operating, accessibility, security, and compliance costs require current project-, jurisdiction-, provider-, and entity-specific review.",
    built: "A browser-based phase editor that sums normalized low/high hours at a user-set rate, supports add and delete, applies an optional generic planning allowance, and exports the working assumptions as a local CSV. The public version does not provide a complete lifecycle budget or quote.",
    serves: "Builders and prospective buyers beginning a scoped estimation conversation.",
    demonstrates: "Commercial modeling, transparent scoping, interaction design, and translation of delivery work into a practical decision tool.",
    evidence: "The labor arithmetic, editable phase model, local CSV export, explicit scope boundary, privacy and terms routes, and safe text rendering are live. The former lead-processing funnel and flat tax calculations were removed. Figures remain illustrative—not quotes, guarantees, tax, financial or legal advice, or independently validated benchmarks.",
    live: "https://ai-budget-calc-red.vercel.app/",
  },
  {
    slug: "source-integrity-audit",
    title: "Source Integrity Audit",
    category: "Evidence + legal operations",
    practice: "Independent",
    status: "Prelaunch manual evidence-review service concept · release-blocked",
    purpose: "Describe a manual source-integrity review service and offer a limited browser-local citation-marker preflight—not technical provenance or authenticity verification.",
    noticed: "AI-assisted documents can contain authorities that do not exist, sources that do not support the attributed proposition, outdated law or science, vague attribution, and claims whose confidence exceeds the underlying evidence. A spot check cannot show which claims were actually reviewed.",
    researched: "The service architecture distinguishes express and implied claims, grades verifiability, prioritizes primary sources, checks date and currency, evaluates attribution, records funding or conflicts, assigns confidence, and produces an evidence-grade summary. The public experience also exposes a limited quick-check tool and the EVIDENCE framework.",
    built: "A documented verification service and public intake surface for checking whether cited authorities exist, are current, and support the proposition attributed to them.",
    serves: "Publishers, law firms, researchers, and trust-sensitive organizations.",
    demonstrates: "Citation verification, evidence provenance, legal-research discipline, and productized quality assurance.",
    evidence: "This portfolio record verifies the public service design, methodology explanation, quick-check interface, deliverables, and stated turnaround structure. It does not independently validate every historical example, performance claim, price, or claimed prior audit result on the underlying commercial page. The service is informational and does not replace filing counsel, editorial judgment, or domain-specific professional review.",
    live: "https://provenance-verify.vercel.app/",
  },
  {
    slug: "one-person-firm-os",
    title: "One-Person-Firm OS",
    category: "Independent work · practice operating-system design",
    practice: "Institutions of One",
    status: "Live service-architecture prototype · remediated August 2026",
    purpose: "Design portable operating infrastructure for solo consultants, fractional executives, creators, and portfolio professionals across positioning, delivery, client operations, evidence, administration, and AI-assisted workflows.",
    noticed: "Independent professionals often accumulate disconnected notes, task managers, client records, AI conversations, and automations. The tools exist, but the work of deciding what belongs where, what should happen next, and how the system stays current remains with the operator.",
    researched: "The concept maps the practice, audiences, offers, obligations, decision rights, information classes, recurring friction, and review needs before proposing a command center or bounded AI assistance. Sensitive-data, vendor, permission, human-review, portability, and offboarding decisions are treated as part of the operating design.",
    built: "A public service-architecture prototype for discovery, scoped system design, configuration with sanitized testing, documentation, training, review, and handoff. It presents possible scope patterns rather than fixed packages or autonomous software.",
    serves: "Solo consultants, fractional executives, creators, portfolio professionals, and other independent operators.",
    demonstrates: "Operational product design, independent-work infrastructure, process architecture, and packaged implementation.",
    evidence: "The live page verifies the service architecture, scope patterns, Institutions of One/Aloha AI boundary, RN authorship, sensitive-data controls, and human-review limits. The former enrollment, contact, checklist, pricing, scarcity, fixed-timeline, and autonomous-operation claims were removed. No availability, checkout, reservation, downloadable template, configured client workspace, or outcome is represented as live.",
    live: "https://opfos-firm.vercel.app/",
  },
  {
    slug: "ai-for-developing-brains",
    title: "AI for Developing Brains",
    category: "Education + neurotechnology",
    practice: "NSAG · M12",
    status: "Public prelaunch workshop architecture · release-blocked",
    purpose: "Explain how children’s developing brains interact with AI without panic, hype, or unsupported certainty.",
    noticed: "Families and schools are being asked to make decisions about child-facing AI while public discussion often collapses into either technological optimism or generalized harm claims. The missing layer is an age- and context-sensitive way to connect what a child is doing with AI to the developing cognitive and physiological systems involved.",
    researched: "The public experience organizes developmental questions around age stage, early-environment stability, caregiver-child interaction, milestone surveillance, institutional and technology-setting design, adversity buffering, and vendor or sponsorship governance. It situates the workshop within NSAG M12 and related nervous-system-aware governance modules.",
    built: "A public prelaunch architecture for a proposed ninety-minute parent and educator workshop connecting developmental neuroscience, AI use, practical boundaries, and family decision-making; delivery, enrollment, and supporting materials are not yet verified.",
    serves: "Parents, caregivers, educators, schools, and youth-serving organizations.",
    demonstrates: "Developmental-neuroscience translation, curriculum design, risk communication, and nervous-system-aware education.",
    evidence: "The live site presents a workshop, guide, assessment dimensions, self-assessment, pricing, and booking or wait-list interfaces. This portfolio record verifies that public product architecture; it does not independently certify every neuroscience claim, citation, outcome promise, availability statement, or fulfillment pathway. The material is educational and not medical advice.",
    live: "https://kids-developing-brains.vercel.app/",
  },
  {
    slug: "transform-drug-market-transition-observatory",
    title: "Transform Drug Market Transition Observatory",
    category: "Drug policy + monitoring",
    practice: "Independent research",
    status: "Static independent monitoring prototype · release-blocked",
    purpose: "Monitor whether drug-market transitions find a workable regulatory balance.",
    noticed: "Drug-policy transitions are often evaluated through isolated legal changes or market headlines even though public-health protection depends on how regulation, commercial power, access, equity, intellectual property, and community authority interact over time. Transform Drug Policy Foundation's published 'sweet spot' framework supplies a coherent way to monitor those interactions without treating either prohibition or unrestricted commercialization as the default success condition.",
    researched: "The observatory operationalizes Steve Rolles and Transform Drug Policy Foundation publications from 2004–2026 across seven monitoring dimensions: corporate capture; patents and intellectual property; Indigenous knowledge and benefit sharing; state equity programs; development impacts; psychedelic commercialization; and Transform's own research and implementation record. The live system also exposes dated updates, source links, alerts, and a weekly-digest architecture.",
    built: "A monitoring observatory organized around Transform Drug Policy Foundation frameworks and the legal, market, public-health, and governance signals that shape transition outcomes.",
    serves: "Drug-policy researchers, regulators, advocates, and institutions evaluating market transitions.",
    demonstrates: "Framework operationalization, longitudinal monitoring, policy synthesis, and public intelligence design.",
    evidence: "This is an independently built monitoring tool informed by Transform Drug Policy Foundation's published work. It is not commissioned by, affiliated with, or endorsed by Transform or Steve Rolles, and it does not speak for them. The portfolio verifies the public framework, seven-tab information architecture, dated source presentation, and alert or digest interfaces—not the continuing accuracy of every statistic, legal development, quotation, scoring judgment, or automated update. It is informational and not legal or policy advice.",
    live: "https://transform-observatory.vercel.app/",
  },
  {
    slug: "zero-to-frontier",
    title: "Zero → Frontier",
    category: "AI education + public resources",
    practice: "Aloha AI",
    status: "Live public guide",
    purpose: "Make the history, concepts, and present frontier of AI understandable through a fully sourced learning path.",
    noticed: "Introductory AI material commonly forces a false choice between simplified marketing content and technical documentation that assumes substantial prior knowledge. It also separates history, practical use, tool selection, governance, and frontier debates, leaving a newcomer without a coherent route through the field.",
    researched: "The guide traces seventeen historical turning points from Turing's 1950 paper through current frontier systems; explains core concepts and working techniques; compares tool categories; and organizes use cases, ten implementation playbooks, eighteen reusable prompt templates, human-review controls, and a searchable library of 237 resources. The sourcing standard favors named primary, official, peer-reviewed, or otherwise attributable materials and surfaces genuine expert disagreement.",
    built: "A free guide moving from Turing’s 1950 thought experiment to frontier models, supported by a library of 237 free resources.",
    serves: "Curious adults, students, professionals, and teams seeking a structured introduction to AI.",
    demonstrates: "Curriculum architecture, technical translation, source curation, and accessible public education.",
    evidence: "The live artifact verifies a public, no-account learning system spanning twenty pages, eleven sections, a routed starting experience, downloadable templates, worked examples, and a searchable resource library. 'Fully sourced' describes the project's editorial standard; this portfolio audit did not independently revalidate all 237 resources or every technical, historical, product, privacy, pricing, or frontier claim. Fast-changing model and vendor information should be checked against the linked current primary source before use.",
    live: "https://zero-to-frontier.vercel.app/",
    source: "https://github.com/rn-collins/zero-to-frontier",
  },
  {
    slug: "psych-ops-directory",
    title: "Psych Ops Directory",
    category: "Psychedelic operations + ecosystem infrastructure",
    practice: "Independent",
    status: "Live directory",
    purpose: "Make the operational infrastructure of the psychedelic ecosystem searchable across legal, financial, clinical, and support functions.",
    noticed: "Psychedelic organizations can identify prominent researchers, clinics, and policy groups more easily than the operational providers needed to form, finance, insure, staff, study, communicate, and govern real work. Those providers are distributed across fields and jurisdictions, and a simple undifferentiated vendor list obscures the difference between a named psychedelic relationship, a verifiable field presence, and an unconfirmed candidate.",
    researched: "The directory classifies 177 listings across twenty-three categories and three evidence tiers. Records combine service descriptions, specialties, locations, pricing signals, and field-specific context; the interface supports keyword and category search, example queries, comparisons, CSV export, new-listing submissions, and flags for review.",
    built: "A curated directory of vendors and organizations across twenty-two operational categories.",
    serves: "Psychedelic organizations, operators, researchers, clinicians, and professional-service providers.",
    demonstrates: "Ecosystem taxonomy, directory architecture, field research, and operational knowledge design.",
    evidence: "The live artifact currently presents 177 records across twenty-three categories and explicitly labels three verification tiers. Inclusion is research evidence, not a recommendation, endorsement, active-license confirmation, conflict check, or guarantee of fit. Provider status, personnel, pricing, jurisdiction, licensure, insurance, and service scope can change; users must independently verify a provider before engagement. The directory is informational and does not provide legal, clinical, financial, or investment advice.",
    live: "https://psych-ops-directory.vercel.app/",
  },
  {
    slug: "set-for-life",
    title: "Set for Life",
    category: "Legal education + career systems",
    practice: "Independent",
    status: "Public prelaunch course prototype · release-blocked",
    purpose: "Turn relationship-building and LinkedIn outreach into a repeatable networking system for law students.",
    noticed: "Law-student career advice often treats networking as a vague social obligation or a last-minute job-search tactic. That leaves students without a target map, research standard, message architecture, follow-up cadence, or feedback loop—and makes the process especially opaque for people without inherited professional networks.",
    researched: "The course translates RN's reported 1L outreach practice into eight modules covering positioning, profile design, target mapping, practitioner research, the six-part Aloha Framework, call conversion, daily operating discipline, and compounding. It pairs that curriculum with a ninety-day calendar, annotated messages, four AI-assisted working projects, and small-batch review of outreach data.",
    built: "A self-serve course grounded in RN’s 1L networking process, outreach data, and resulting opportunities.",
    serves: "Law students who need a practical relationship-building system beyond job-board applications.",
    demonstrates: "Experience-to-curriculum translation, career-system design, evidence-backed instruction, and productization.",
    evidence: "The live page verifies the course thesis, eight-module curriculum, included-tool architecture, pricing and refund language, and a stated future-cohort offer. Outreach volumes, reply rates, testimonials, positions obtained, and causal claims are RN's self-reported experience and have not been independently audited; they are not promises that another student will achieve the same result. Enrollment, delivery, lifetime-update, refund, and launch representations require confirmation through the underlying commercial workflow. The working `-black` URL is retained because the page's declared canonical URL currently resolves to an unrelated application.",
    live: "https://set-for-life-black.vercel.app/",
  },
  {
    slug: "psychonaut-bookworm",
    title: "The Psychonaut Bookworm",
    category: "Publishing + media systems",
    practice: "Fat Nugs Magazine concept",
    status: "Live media-library concept",
    purpose: "Turn psychedelic literature into a structured, reusable media and editorial system.",
    noticed: "A reading list preserves titles but not the many reusable connections inside a body of literature: historical actors, scientific claims, quotations, geographies, primary documents, disputed interpretations, and relationships across books. Editorial teams need a system that can turn those connections into multiple formats without losing the source trail.",
    researched: "The library maps psychedelic books and source material into fourteen editorial formats, including long-form writing, quotation cards, then-versus-now annotations, flashcards, mini-essays, primary-document commentary, character profiles, passage spotlights, geography pieces, cross-book bridges, reading lists, science annotations, NotebookLM packs, and an eight-course free-university layer.",
    built: "A media library presenting 1,399 planned or finished-format pieces across fourteen content types tied to psychedelic literature.",
    serves: "Editors, readers, educators, publishers, and psychedelic-literature communities.",
    demonstrates: "Editorial systems design, content atomization, knowledge organization, and scalable media planning.",
    evidence: "The live artifact verifies an interactive catalog presenting 1,399 entries across fourteen formats, format-level counts, a guided reading-list request, and cross-links to related research infrastructure. This audit does not independently certify the completeness, publication status, scientific accuracy, quotation context, rights clearance, or source support of every entry. The project states that it is independent, not publisher-affiliated or endorsed, may contain affiliate links, and is editorial—not clinical, legal, or therapeutic—material.",
    live: "https://psychonaut-bookworm.vercel.app/",
  },
  {
    slug: "startup-legal-risk-monitor",
    title: "Startup Legal Risk Monitor",
    category: "Legal intelligence + monitoring",
    practice: "Aloha AI",
    status: "Live controlled prototype · noindex",
    purpose: "Track regulatory signals that can alter a startup’s legal and operating risk.",
    noticed: "Early-stage teams can move from product decision to launch faster than they can monitor the regulatory sources that govern fundraising, consumer protection, financial products, data practices, and automated decision-making. The practical gap is not a lack of public information; it is knowing that a new filing, enforcement action, guidance document, or bill is important enough to bring to counsel.",
    researched: "The monitor is organized around SEC filings and rulemaking, FTC enforcement, CFPB guidance, federal AI-governance proposals, and state AI legislation. Its triage model separates action-relevant developments from moving issues and background context through Immediate, Watch, and Info tiers, with an intended public-government-source ingestion and weekly-alert layer.",
    built: "A monitoring interface covering SEC filings, FTC enforcement, CFPB guidance, and AI legislation with alert-oriented presentation.",
    serves: "Founders, startup counsel, compliance teams, and investors.",
    demonstrates: "Regulatory monitoring, legal taxonomy, risk communication, and decision-support design.",
    evidence: "The live prototype verifies the five-source-category architecture, risk-tier definitions, explanatory guidance, subscription interface, and legal-advice boundary. During this audit, the Active Signals area remained in a loading or empty state, so hourly ingestion, signal completeness, freshness, tier accuracy, and email delivery are not represented as operationally verified. Government feeds and legal status can change, and every signal requires confirmation against the controlling primary source and qualified counsel before action.",
    live: "https://legal-risk-monitor.vercel.app/",
  },
  {
    slug: "nervous-system-studio",
    title: "Nervous System Studio",
    category: "Neuroscience + environment design",
    practice: "Independent",
    status: "Live interactive guide",
    purpose: "Help people design sensory environments and routines around calm, focus, creativity, and sleep.",
    noticed: "People often know that certain rooms, routines, sounds, lighting conditions, or levels of stimulation affect how they feel, but those observations remain anecdotal and difficult to compare. Generic wellness and décor advice also tends to prescribe a supposedly ideal environment rather than helping a person examine patterns in their own experience.",
    researched: "The experience models sensory inputs—including light, sound, scent, clutter, routine, and optional cannabis context—alongside self-reported states such as calm, focus, creativity, sleep, and overstimulation. It uses a sensory profile, repeated moment logs, cautious association language, single-variable experiments, and four environment blueprints while keeping preview data in the user's browser.",
    built: "An interactive environment-and-routine design experience translating nervous-system considerations into practical choices.",
    serves: "Individuals seeking more supportive home, work, and daily sensory environments.",
    demonstrates: "Neuroscience translation, personalized interaction design, environmental thinking, and public education.",
    evidence: "The live research preview verifies the sensory-profile flow, local-device storage design, moment logging, rules-based pattern language, four blueprint concepts, optional cannabis input, research page, privacy explanation, and safety disclaimers. Its outputs are self-reflection prompts based on user-entered associations—not diagnoses, causal findings, treatment recommendations, or proof that an environmental change improves a health condition. The displayed testimonial is explicitly a composite illustration, and the beta, wait-list, and future service claims require separate fulfillment review.",
    live: "https://nervous-system-studio.vercel.app/",
  },
  {
    slug: "psychedelic-law-library",
    title: "The Psychedelic Law Library",
    category: "Law + public knowledge infrastructure",
    practice: "Independent",
    status: "Live public library",
    purpose: "Make psychedelic law understandable across state programs, professional roles, business questions, and failure scenarios.",
    noticed: "Public discussion regularly collapses four different legal conditions—legal, decriminalized, regulated, and approved—into a single idea. In psychedelics, that confusion compounds across federal law, state programs, local reforms, professional licensure, religious-use claims, clinical research, and business operations, making it difficult for a reader to identify both the governing question and the kind of lawyer they may need.",
    researched: "The library organizes 143 plain-English articles around foundational distinctions and seven reader pathways: participants, people responding to harm, facilitators, clinicians, operators, researchers or investors, and people exploring religious use. Coverage includes Oregon and Colorado programs, federal-state conflict, licensing and scope, service-center operations, trials and biotechnology, RFRA questions, disputes, and lawyer-selection guidance, with article-specific review dates.",
    built: "A structured library of 143 plain-English articles covering Oregon and Colorado programs, facilitators, clinicians, businesses, research, and remedies.",
    serves: "Practitioners, operators, researchers, students, policymakers, and the public.",
    demonstrates: "Legal knowledge architecture, plain-language communication, issue taxonomy, and scalable public education.",
    evidence: "The live artifact verifies a searchable 143-article index, seven audience routes, article pages, review-date conventions, and a prominent legal-information boundary. This portfolio audit does not independently cite-check all articles, confirm that every page remains current, or establish an attorney-client relationship. Psychedelics law changes quickly and varies by jurisdiction and facts; users must confirm time-sensitive propositions against current statutes, regulations, agency materials, cases, and licensed counsel.",
    live: "https://law-communication-library.vercel.app/",
  },
  {
    slug: "eolpc-knowledge-system",
    title: "EOLPC Knowledge System",
    category: "Clinical evidence + AI retrieval",
    practice: "Independent",
    status: "Live controlled prototype · noindex",
    purpose: "Retrieve current primary sources for psychedelic end-of-life care questions.",
    noticed: "Research relevant to psychedelic end-of-life care is dispersed across journal databases, trial registries, legal frameworks, course materials, practitioner knowledge, and community experience. A family member, clinician, educator, or practitioner may need a sourced starting point without having the time or database fluency to search each system separately, while patient-specific questions require a human clinical boundary rather than an automated answer.",
    researched: "The proposed system separates five knowledge layers: qualitative interviews, practitioner-survey data, EOLPC curriculum, permission-based professional discussions, and jurisdiction-specific legal or policy materials. The working retrieval prototype searches PubMed, Semantic Scholar, Europe PMC, ClinicalTrials.gov, and Exa in parallel, then distinguishes research-backed questions from patient-specific or out-of-scope requests that should route to a practitioner directory.",
    built: "An AI-assisted knowledge interface connected to live PubMed and ClinicalTrials.gov source pathways.",
    serves: "Researchers, clinicians, educators, and teams studying psychedelic end-of-life care.",
    demonstrates: "Clinical evidence retrieval, source grounding, sensitive-domain interface design, and knowledge-system prototyping.",
    evidence: "The public page verifies a controlled proposal and retrieval demonstration, a five-layer RAG architecture, example queries, source-pathway descriptions, patient-specific refusal design, proposed access roles, screens, budget paths, and nine-month build plan. It does not verify that the proposed private knowledge layers have been licensed, permissioned, ingested, or deployed; that every generated response is complete or error-free; or that the displayed production metrics and screen examples are live operational data. It is not a clinical tool or medical or legal advice, and source links and time-sensitive claims require primary-source review.",
    live: "https://eolpc-demo.vercel.app/",
  },
  {
    slug: "entheogen-atlas",
    title: "Entheogen Atlas",
    category: "Psychoactive-plant science + history",
    practice: "Independent",
    status: "Controlled multidisciplinary atlas prototype · high-risk features release-blocked",
    purpose: "Map sacred plants and substances across archaeology, neuroscience, phenomenology, religious use, law, and clinical science.",
    noticed: "Psychoactive substances are commonly discussed inside a single frame—criminal law, clinical development, pharmacology, spirituality, or popular culture—even though their contemporary status emerges from interactions among all of them. Separating those histories can erase Indigenous traditions, overstate clinical certainty, or make modern prohibition appear older and more uniform than it is.",
    researched: "The atlas connects ten substances with six historical timelines and research domains spanning archaeology, receptor pharmacology, phenomenology, clinical trials, criminalization, religious exemptions, Indigenous and cultural use, global legal frameworks, decriminalization, drug interactions, and key researchers. Interactive layers include comparisons, legal-status views, an RFRA issue-spotter, risk and dose tools, a glossary, timelines, and citation-oriented reference material.",
    built: "A multidisciplinary research atlas spanning ten substances and a long historical timeline.",
    serves: "Readers, researchers, educators, journalists, and psychoactive-plant communities.",
    demonstrates: "Cross-disciplinary synthesis, research-atlas design, scientific and legal translation, and long-form public scholarship.",
    evidence: "The live artifact verifies the ten-substance structure, six timelines, multidisciplinary research sections, comparison interfaces, legal and RFRA issue-spotting tools, dose and interaction references, safety notices, and citations presented by the site. This audit does not independently validate every archaeological date, Indigenous or religious characterization, molecular or receptor claim, clinical statistic, legal status, dose range, interaction warning, editorial score, or assertion that every citation is primary. Several displays identify their own 2025 or 2026 currency limits. The atlas is educational and harm-reduction reference—not medical or legal advice—and culturally sensitive claims require engagement with the relevant peoples and authorities.",
    live: "https://entheogen-atlas.vercel.app/",
  },
  {
    slug: "cannabis-healthcare-impact-assessment",
    title: "Cannabis Healthcare Education Impact Assessment",
    category: "Cannabis education + evaluation",
    practice: "NSAG applied",
    status: "NSAG research component · collection held · release-blocked",
    standalone: false,
    promoteLive: false,
    purpose: "Measure whether cannabis-healthcare education changes knowledge, confidence, or intended behavior.",
    noticed: "Cannabis-healthcare education is often evaluated through attendance or immediate satisfaction even though the more consequential questions are whether people understand disclosure and interaction risks, feel safer speaking with a provider, and later change what they do in an actual care setting. A single post-event survey cannot distinguish prior knowledge from session-associated change or intention from behavior.",
    researched: "The instrument uses a matched pre/post design with Knowledge, Attitude, and Behavior subscales, followed by Outcome, Confidence, Motivation, Barriers, stage-of-change items, and an optional one-to-three-month follow-up. It collects optional demographic and care context, groups responses through event codes, normalizes item scores, and proposes matched-pair, regional, legal-status, and intention-to-action analysis. The public methodology identifies Jacques et al. (2025) as a comparable continuing-education precedent and defines publication-readiness thresholds.",
    built: "An anonymous pre/post assessment experience for education sessions.",
    serves: "Healthcare educators, institutions, participants, and program evaluators.",
    demonstrates: "Evaluation design, behavior-change measurement, health education, and usable assessment infrastructure.",
    evidence: "The live artifact verifies the participant intake, optional-context fields, pre/post selection, public study explanation, scoring model, follow-up concept, session-code architecture, publication thresholds, and stated anonymity boundary. This audit does not validate the instrument psychometrically, establish IRB approval or research consent sufficiency, confirm secure storage or researcher-dashboard operation, verify collected sample sizes, or show that the tour produced any measured effect. The named comparison study does not itself validate this adapted instrument. The experience is informational and not medical advice.",
    live: "https://dru-assessment.vercel.app/",
  },
  {
    slug: "destigmatization-toolkit",
    title: "Destigmatization Toolkit for Psychoactive Plant Medicine",
    category: "Law + science + public communication",
    practice: "Organization-specific concept",
    status: "Live concept · independently initiated",
    purpose: "Give different audiences a source-grounded way to discuss psychoactive plant medicine without flattening pharmacology, law, history, or policy.",
    noticed: "Arguments about psychoactive plant medicine routinely fail because clinicians, policymakers, religious communities, lawyers, journalists, and general readers enter through different concerns and standards of proof. A single advocacy narrative can overstate clinical evidence, ignore legal exposure, erase Indigenous authority, or use language that alienates the audience before the underlying evidence is considered.",
    researched: "The toolkit organizes twenty-nine sections and 222 cited sources across stigma architecture, pharmacology, research history, substance profiles, federal and state law, implementation data, economics, safety, evidence quality, audience-specific communication, Indigenous communities, language, impermissible claims, religious use, intellectual property, access, insurance, criminal defense, practitioner compliance, business formation, tourism, youth considerations, funding, and recent RFRA litigation. Six audience paths reorder that same evidence for different starting questions.",
    built: "A 222-source reference organized into twenty-nine sections for six audiences.",
    serves: "Legal professionals, clinicians, policymakers, educators, advocates, and the public.",
    demonstrates: "Primary-source synthesis, audience-specific translation, stigma-aware communication, and large-scale reference design.",
    evidence: "The live artifact verifies a navigable twenty-nine-section reference, six audience routes, endnote area, legal and medical disclaimers, institutional and author attribution, and the presentation of 222 sources. It is independently initiated and is not represented as commissioned client work. This portfolio audit does not independently cite-check all 222 sources, validate every clinical or policy claim, confirm that every citation is primary, establish cultural authority, or treat collaboration language as endorsement by every named person or institution. Time-sensitive law and science require current primary-source and professional review.",
    live: "https://destig-toolkit.vercel.app/",
  },
  {
    slug: "evidence-studio",
    title: "Evidence·Studio",
    category: "Brand strategy + evidence governance",
    practice: "Independent",
    status: "Live practice concept",
    purpose: "Ground creator and brand strategy in evidence, disclosure, and governance for trust-sensitive markets.",
    noticed: "Creator and brand programs in regulated or credibility-sensitive markets are often optimized for attention while founder preference, weak audience assumptions, inconsistent disclosures, unsupported claims, and unclear approval rules remain untreated. Engagement metrics can then make an incoherent or risky system appear successful without showing whether it builds durable trust.",
    researched: "The practice model treats customer, market, behavioral, performance, internal, and external-research evidence as distinct inputs that must be graded for strength, recency, relevance, and directness. Its six-phase method moves from diagnosis and evidence grading through hypothesis, design, testing, and governance, with service architectures for a flagship audit, partnership strategy, operating rules, expert-led thought leadership, and continuing advisory support.",
    built: "A strategy practice surface connecting brand decisions, creator relationships, legal disclosure, and evidence standards.",
    serves: "Health, legal, wellness, and other trust-sensitive brands and creators.",
    demonstrates: "Brand-system design, evidence governance, disclosure architecture, and market-specific positioning.",
    evidence: "The live multi-page concept verifies the positioning, evidence taxonomy, six-phase method, service menu, audit and deliverable descriptions, insight library, request flow, and explicit legal-advice boundary. It does not demonstrate completed client engagements, validated conversion or trust outcomes, independently tested recommendations, or legal review of a particular campaign. FTC, platform, claims, privacy, and endorsement requirements change and must be reviewed for each engagement; the service architecture is not a substitute for counsel.",
    live: "https://creator-brand-evidence.vercel.app/",
  },
  {
    slug: "aloha-build-club",
    title: "Aloha Build Club",
    category: "Community + AI building",
    practice: "Aloha AI",
    status: "Prelaunch community and membership architecture · release-blocked",
    purpose: "Create a recurring room where people building with AI can work alongside others, get unstuck, and ship.",
    noticed: "AI lowers the cost of producing ideas and drafts but does not create the routine, social presence, next-step clarity, or accountability required to finish them. Independent builders can therefore accumulate a 'someday pile' of nearly complete work even when lack of technical skill is not the primary obstacle.",
    researched: "The membership concept combines a structured sixty-minute room, host-plus-AI unblocking, heads-down body doubling, a public moment of completion, an engagement pod, progress nudges, and a weekly shipped list. The public rationale links peer-effect, goal-accountability, cooperation, and external body-doubling evidence while explicitly distinguishing stronger presence and accountability findings from the thinner controlled evidence for body doubling itself.",
    built: "A body-doubling and build-community experience with a recurring participation model.",
    serves: "Independent builders, professionals, and people learning to make with AI.",
    demonstrates: "Community-product design, facilitation architecture, accountability systems, and accessible AI participation.",
    evidence: "The live page verifies the room format, membership and tier concepts, intended cohort cap, cited public rationale, audience boundaries, privacy language, FAQ structure, and three advertised price points. It does not verify an active cohort, scheduled daily rooms, recordings, engagement pod, shipped-list history, member outcomes, subscription processing, cancellation operations, or fulfillment of annual and Pro benefits. During inspection, enrollment calls to action appeared as buttons rather than verified checkout destinations. The cited studies support parts of the design rationale; they do not prove the club's effectiveness or guarantee productivity, shipping, income, or any other outcome.",
    live: "https://aloha-build-club.vercel.app/",
  },
  {
    slug: "regac",
    title: "REGAC — Regulatory-Education Curriculum Concept",
    category: "Legal education + compliance",
    practice: "Independent",
    status: "Public prelaunch curriculum concept · commercial and CLE release-blocked",
    purpose: "Teach cannabis and psychedelics regulatory compliance through an intensive, implementation-oriented program.",
    noticed: "Emerging-therapeutics compliance education can age quickly and often teaches rules without the institutional logic behind rulemaking, enforcement, agency comments, filing review, or federal-state conflict. Practitioners and operators need a method for returning to controlling sources and identifying what an agency is actually responding to—not merely another static overview.",
    researched: "The proposed curriculum spans state licensing, DEA scheduling and federal overlays, operator compliance, emerging therapeutics, agency decision-making, primary-source monitoring, and an AI-governance track addressing existing FTC, FDA, and state authority. Its delivery architecture combines four live sessions, recordings and summaries, a Notion hub, four source-grounded NotebookLM packs, certificate paths, Q&A, and a claimed 216-template library, with individual, firm, and institutional tiers.",
    built: "A public landing-page prototype for a proposed four-module, source-governed regulatory-education curriculum.",
    serves: "Attorneys, compliance professionals, operators, and regulated-market teams.",
    demonstrates: "Regulatory curriculum design, template systems, professional education, and compliance translation.",
    evidence: "The remediated public page verifies a prelaunch curriculum concept, four proposed learning modules, a visible development boundary, an RN authorship block, and policy routes. It does not offer enrollment, payment, a cohort, templates, course access, certificates, or CLE credit. The curriculum, source register, learning materials, ownership and confidentiality review, qualified professional review, learner terms, and delivery system remain to be completed before any commercial or credentialed launch.",
    live: "https://regac-academy.vercel.app/",
  },
  {
    slug: "narch",
    title: "NARCH — Neuroarchitecture Advisory",
    category: "Neuroscience + built environment",
    practice: "NSAG applied",
    status: "NSAG applied component · release-blocked",
    standalone: false,
    promoteLive: false,
    purpose: "Ground built-environment decisions in peer-reviewed neuroscience and auditable evidence.",
    noticed: "Architecture and planning teams often invoke wellbeing, biophilia, cognition, or healing without a traceable link between a specific design choice, a specific source, and an observable post-occupancy result. The problem is not simply access to research; it is the absence of governance infrastructure that makes a design rationale reviewable across clients, grantmakers, planning bodies, and building users.",
    researched: "NARCH applies NSAG modules M5, M7, and M10 through six assessment dimensions: evidence documentation, biophilic-design integration, acoustic and sensory governance, post-occupancy evaluation, equity and access, and grant or approval documentation. The public concept also distinguishes direct, indirect, and spatial biophilic elements; separates input-oriented certifications from measured outcomes; and proposes evidence grading and primary-source briefs as the connective tissue between research and design decisions.",
    built: "An advisory framework for translating neuroscience into client, design, and grant-facing built-environment decisions.",
    serves: "Architects, developers, institutions, designers, and funders.",
    demonstrates: "Neuroscience synthesis, built-environment governance, audit-ready evidence, and applied-practice design.",
    evidence: "The live NSAG-applied concept verifies the six-dimension framework, readiness diagnostic, signal-versus-noise guidance, glossary, hypothetical before-and-after examples, engagement architecture, and proposed Biophilic Evidence Audit. It does not verify that an audit, advisory engagement, workshop, post-occupancy evaluation, grant filing, or cited outcome has been delivered or independently validated. Claims about study volume, biological effects, percentage outcomes, standards, certifications, and source currency require source-by-source scientific and professional review before use in a project. NARCH does not establish architectural licensure, accreditation, regulatory approval, or a guarantee of health, cognitive, planning, grant, or building-performance outcomes.",
    live: "https://narch-advisory.vercel.app/",
  },
  {
    slug: "burgermeister-expansion-intel",
    title: "Burgermeister Expansion Intel",
    category: "Market expansion + regulatory intelligence",
    practice: "Organization-specific concept",
    status: "Live concept · independently initiated",
    purpose: "Track legal and regulatory signals affecting international market entry.",
    noticed: "International restaurant expansion turns a growth plan into a coordinated legal-operations problem: market entry, leases, employment, food and allergen rules, cross-border supply, trademarks, privacy, AI use, and consumer obligations arrive on different clocks and in different jurisdictions. A conventional memo can identify issues once; an operating team needs a system that preserves sources, urgency, ownership, and counsel-escalation decisions over time.",
    researched: "Using publicly available information, the concept maps an expansion scenario across the United Kingdom, European Union, United States, Germany, Poland, and possible future markets. Its 27-signal model scores impact, complexity, and urgency; distinguishes critical, high, medium, and low items; identifies issues requiring outside counsel; and connects each signal to a source library and proposed next action.",
    built: "A multi-jurisdiction expansion-intelligence interface covering the United States, United Kingdom, Germany, and Poland.",
    serves: "A restaurant group evaluating international expansion and the advisors supporting it.",
    demonstrates: "Organization-specific research, cross-border issue mapping, regulatory intelligence, and pre-proposal product design.",
    evidence: "The live prototype verifies a dashboard with 27 displayed signals, priority and jurisdiction taxonomies, outside-counsel flags, a 17-source library concept, searchable signal views, an add-signal workflow, and descriptions of optional Slack and email alerts. It is independently initiated from public information and was not commissioned, reviewed, endorsed, or adopted by Burgermeister; it does not contain or evidence access to the company's internal plans, data, counsel, or compliance program. Dates, expansion statements, revenue figures, duties, thresholds, and legal conclusions shown in the prototype require current primary-source verification and qualified local counsel before action. The scoring system is issue-spotting and prioritization—not legal advice, a complete diligence report, or proof that monitoring and alerts operate continuously.",
    live: "https://bm-intel-ivory.vercel.app/",
  },
  {
    slug: "psych-ops-intel",
    title: "Psych Ops Intel",
    category: "Psychedelic regulation + monitoring",
    practice: "Independent",
    status: "Live regulatory monitor",
    purpose: "Surface primary-source psilocybin regulatory updates across active state systems.",
    noticed: "State psilocybin programs evolve through agency pages, rulemaking notices, licensing windows, fee changes, and program-specific announcements that do not arrive in one shared channel. Operators and practitioners can therefore miss a deadline or proposed change even when the controlling information is public.",
    researched: "The monitor is organized around six named regulator and funder sources: Oregon Health Authority; Colorado DORA and the Department of Revenue Natural Medicine Division; New Mexico's health authority or program surface; the Psychedelic Science Funders Collaborative; and Healing Advocacy Fund. Updates are assigned urgent, watch, or stable status and grouped by source so a reader can separate deadline-bound compliance signals from pending changes and general field information.",
    built: "A weekly monitoring interface for Oregon, Colorado, and New Mexico psilocybin programs and related policy or funding sources.",
    serves: "Psychedelic operators, attorneys, researchers, educators, and policy teams.",
    demonstrates: "Primary-source monitoring, regulatory taxonomy, update automation, and field-intelligence delivery.",
    evidence: "The inspected live interface displays a dated sweep, six source filters, 47 update cards, urgency filtering, an explanatory methodology, subscription concept, and links to related field infrastructure. The page states that an automated sweep runs Mondays at 9:00 UTC and falls back to a labeled last-verified dataset; this inspection confirms the representation and rendered dataset, not the scheduler, scraper, source coverage, alert delivery, failure handling, or week-over-week freshness. Several visible items are secondary commentary or broad field news despite the primary-source positioning, so each action-affecting item must be traced to the controlling agency source. The monitor is informational issue-spotting, not legal advice, a comprehensive regulatory service, or a guarantee that a deadline or rule change will be captured.",
    live: "https://psychops-intel.vercel.app/",
  },
  {
    slug: "gapi",
    title: "GAPI — AI Agent Governance Infrastructure",
    category: "AI governance + assessment",
    practice: "NSAG applied",
    status: "Framework and readiness-prototype concept · release-blocked",
    purpose: "Evaluate agent architecture through nervous-system-aware governance dimensions and make governance evidence legible to enterprise users.",
    noticed: "AI-agent assurance is frequently reduced to model capability, output accuracy, or general ethics language even though deployed conversational systems also shape attention, cognitive load, trust, choice architecture, and emotional state. Organizations need a way to document those influence mechanisms, connect them to human oversight, and monitor how they change after deployment.",
    researched: "GAPI extends NSAG modules M2 and M11 into six assessment dimensions: influence-profile documentation, cognitive-load governance, transparency and explainability, human oversight and override, demographic and population impact, and post-deployment monitoring. The concept places those dimensions alongside public signals such as the NIST AI Risk Management Framework and FTC enforcement while proposing an infrastructure-level implementation rather than a periodic policy-only review.",
    built: "A six-dimension NSAG governance assessment and certification-mark concept for AI agents.",
    serves: "AI product teams, enterprise buyers, governance leaders, and assurance functions.",
    demonstrates: "AI-agent governance, assessment design, certification architecture, and translation of institutional theory into product controls.",
    evidence: "The live NSAG-applied concept verifies the six-dimension assessment architecture, readiness diagnostic, signal-versus-noise guidance, glossary, hypothetical transformations, tiered engagement model, and proposed Agent Governance Certification mark and MCP-server direction. It does not verify a functioning governance API or MCP server, completed technical integration, customer assessment, audited model, certification decision, monitoring system, buyer acceptance, or safety outcome. The mark is a proposed NSAG program—not independent accreditation, regulatory approval, an industry standard, or a guarantee that an agent is safe, lawful, unbiased, or suitable for a particular use. Legal, scientific, security, demographic-impact, and assurance claims require domain review and empirical validation.",
    live: "https://gapi-governance.vercel.app/",
  },
  {
    slug: "womens-neuro-health",
    title: "WNH — Women’s Neuro-Health",
    category: "Women’s health + primary-source guidance",
    practice: "NSAG applied",
    status: "NSAG applied component · release-blocked",
    standalone: false,
    promoteLive: false,
    purpose: "Organize primary-source guidance around women’s neurological and nervous-system health.",
    noticed: "Women and clinicians encounter cannabis and psychedelic questions in real care contexts, but the relevant neuroscience is scattered, unevenly sex-disaggregated, and often difficult to translate across hormonal context and life stage. General-population guidance can obscure where evidence is female-specific, where it comes from animal or survey research, and where clinically useful conclusions remain uncertain.",
    researched: "WNH applies NSAG modules M3, M4, and M9 through six dimensions: sex-disaggregated evidence standards, life-stage differentiation, disclosure safety, clinician competency, psychiatric-risk communication, and patient-facing communication. The public evidence library demonstrates an intended method of annotating primary sources by study type, finding, limitation, and evidence grade rather than presenting all citations as equally conclusive.",
    built: "A public guidance experience connecting evidence, life-stage context, and practical next questions.",
    serves: "Women, caregivers, clinicians, educators, and health-system stakeholders.",
    demonstrates: "Women’s-health evidence synthesis, audience-sensitive communication, and public guidance design.",
    evidence: "The live NSAG-applied concept verifies the six-dimension framework, four-volume guide-series proposal, annotated evidence examples, readiness diagnostic, signal-versus-noise section, glossary, hypothetical examples, and engagement interface. It does not establish that the paid guides are complete, clinically reviewed, purchasable, delivered, or used in care; that the evidence library is exhaustive or continuously current; or that any intervention is safe or effective for an individual. Some displayed sources are animal, small-sample, survey, or early-stage evidence and cannot support universal dosing, treatment, risk, or life-stage conclusions. WNH is educational, not medical advice, diagnosis, informed consent, patient-specific decision support, or a substitute for qualified clinical care and current source review.",
    live: "https://wnh-guide.vercel.app/",
  },
  {
    slug: "sport-nsag",
    title: "SPORT — Nervous-System-Aware Athletic Governance",
    category: "Sport + institutional governance",
    practice: "NSAG applied",
    status: "Public applied-framework concept · assessment and commercial release blocked",
    purpose: "Apply Nervous-System-Aware Governance to athletic institutions and athlete welfare.",
    noticed: "Sports organizations govern athlete nervous-system inputs through schedules, travel, training and recovery expectations, facilities, organizational culture, media obligations, and career transitions, yet those decisions are usually separated across coaching, operations, welfare, and communications. That fragmentation can hide cumulative load and make performance or wellbeing effects difficult to document as institutional outputs.",
    researched: "SPORT applies NSAG modules M5, M8, and M15 through six assessment dimensions: physical environment; schedule and recovery; travel and logistical stress; psychological safety and culture; media and public-facing stress; and development and career transition. The public framework distinguishes adaptive from impairing stress, places developmental stage and athlete agency inside governance, and proposes source-backed policies and outcome measures instead of treating awareness or wearable data as sufficient evidence.",
    built: "A six-dimension governance system spanning load, recovery, scheduling, travel, cognitive performance, psychological environments, and organizational culture.",
    serves: "Athletic organizations, teams, governing bodies, coaches, and athlete-welfare leaders.",
    demonstrates: "Framework extension, sport governance, welfare-system design, and institution-level assessment.",
    evidence: "The live NSAG-applied concept verifies the six-dimension framework, five-question readiness diagnostic, signal-versus-noise guidance, glossary, hypothetical before-and-after examples, proposed Athlete's Nervous System Audit, ninety-day roadmap, and tiered engagement architecture. It does not verify an assessment, team or league engagement, client pipeline, completed audit, roadmap implementation, improved performance, reduced injury, athlete-welfare outcome, or institutional adoption. References to F1, LA28, NCAA materials, study findings, risk percentages, and evidence currency require direct source verification and should not imply affiliation, access, endorsement, or a validated causal effect. SPORT is an institutional-design and assessment concept—not medical care, coaching, legal advice, accreditation, or a guarantee of health or competitive outcomes.",
    live: "https://sport-nsag.vercel.app/",
  },
  {
    slug: "inflection-radar",
    title: "Inflection Radar",
    category: "Growth intelligence + governed research",
    practice: "Organization-specific concept",
    status: "Live decision room · independently initiated proposal",
    purpose: "Help a health-communications organization identify emerging neuropsychiatry opportunities before they become ordinary pursuits while preserving source rights, confidence, contradictions, and human authority.",
    noticed: "Real Chemistry publicly evidenced substantial analytics, communications, access, media, and growth capabilities, but its public materials did not establish the exact upstream workflow used to identify and govern prospective-account signals. That was treated as an internally unknown question—not as proof that no such capability exists.",
    researched: "The proposal used permitted public sources to map Real Chemistry's visible capabilities, the neuropsychiatry opportunity environment, source-permission constraints, evidence tiers, human review gates, and the operating decisions required for an eight-week pilot.",
    built: "An independently initiated proposal package: a role-aware interactive decision room, illustrative score, source-permission explorer, proposed eight-week execution model, executive brief, report, and meeting deck.",
    serves: "Growth, strategy, analytics, business-development, legal, privacy, and executive reviewers evaluating whether to authorize a governed public-source pilot.",
    demonstrates: "Public-source organizational diligence, opportunity sensing, evidence and rights governance, human-reviewed scoring, proposal architecture, executive communication, and the conversion of research into a decision-ready interactive system.",
    evidence: "The system is a public-source proposal prepared independently for discussion with Real Chemistry. It is not commissioned work, a representation of Real Chemistry's internal systems, or a statement that publicly unverified capabilities do not exist. It excludes internal, client-confidential, patient-level, licensed-restricted, and other nonpublic information.",
    live: "https://inflection-radar-real-chemistry.vercel.app/",
    source: "https://github.com/rn-collins/inflection-radar-real-chemistry",
    artifacts: [
      { label: "Read executive brief", href: "https://inflection-radar-real-chemistry.vercel.app/assets/executive-brief.pdf" },
      { label: "Read full report", href: "https://inflection-radar-real-chemistry.vercel.app/assets/full-report.pdf" },
      { label: "Open meeting deck", href: "https://inflection-radar-real-chemistry.vercel.app/assets/meeting-deck.pptx" },
    ],
  },
  {
    slug: "creator-rights-framework",
    title: "Creator Rights Issue Spotter",
    category: "Creator economy + governance",
    practice: "Aloha AI",
    status: "Live browser-local educational issue spotter",
    purpose: "Put rights, disclosure, compensation, data, and AI-use questions in front of creator activation decisions.",
    noticed: "Creator activations can combine human or synthetic personas, AI-generated content, likeness rights, music provenance, sponsorship disclosures, multiple platform policies, and cross-border rules within one campaign. Standard influencer checklists and pre-generative-AI agreements may therefore miss who authorized what, which disclosure applies in each format, and when specialist review is required before activation.",
    researched: "The diagnostic organizes seven issue-spotting gates around creator type, AI-contract language, written authorization for likeness use, format-specific FTC disclosure, music licensing and provenance, European-market exposure, and platform-specific AI labeling. Its response logic converts answers into a pre-activation remediation list and escalates selected issues to legal review rather than averaging them into a generic risk score.",
    built: "A seven-question browser-local educational issue spotter covering creator type, AI terms, likeness or voice use, disclosures, music, EU exposure, and platform-policy review.",
    serves: "Creators, brands, agencies, legal teams, and partnership leaders.",
    demonstrates: "Creator-rights issue spotting, governance-by-design, legal research, and practical decision-tool construction.",
    evidence: "The remediated live tool verifies seven question paths, conditional issue prompts, a no-clearance result boundary, restart control, related links, a no-data LinkedIn contact path, visible RN authorship, and privacy, terms, robots, and sitemap routes. The former automated regulatory-feed presentation is suppressed. The tool does not inspect documents or establish ownership, consent, disclosure adequacy, substantiation, platform approval, rights clearance, legal compliance, or permission to publish; current matter-specific review remains required.",
    live: "https://aloha-creator-rights.vercel.app/",
  },
];

export function getPublicBuild(slug: string) {
  return publicBuilds.find((build) => build.slug === slug);
}
