export type PublicationArticle = {
  title: string;
  href: string;
  date: string;
  publication: "Fat Nugs Magazine" | "Cannabis Law Report" | "Cannabis Law Journal";
  series: string;
  byline: string;
  note?: string;
};

export const publicationArchive: PublicationArticle[] = [
  { date: "2025-10-21", publication: "Fat Nugs Magazine", series: "Cannabis, Psychedelics + the Endocannabinoid Link", byline: "RN Collins", title: "Cannabis, Psychedelics, and the Endocannabinoid Link: Part 1", href: "https://www.fatnugsmag.com/cannabis-psychedelics-and-the-endocannabinoid-link-part-1/" },
  { date: "2025-10-29", publication: "Fat Nugs Magazine", series: "Cannabis, Psychedelics + the Endocannabinoid Link", byline: "RN Collins", title: "Cannabis, Psychedelics, and the Endocannabinoid Link: Part 2", href: "https://www.fatnugsmag.com/cannabis-psychedelics-and-the-endocannabinoid-link-part-2/" },
  { date: "2025-11-06", publication: "Fat Nugs Magazine", series: "Cannabis, Psychedelics + the Endocannabinoid Link", byline: "RN Collins", title: "Cannabis, Psychedelics, and the Endocannabinoid Link: Part 3", href: "https://www.fatnugsmag.com/cannabis-psychedelics-and-the-endocannabinoid-link-part-3/" },
  { date: "2026-01-13", publication: "Fat Nugs Magazine", series: "Cannabis + the Body", byline: "RN Collins", title: "Cannabis and the Body: Stretching High, Part 1", href: "https://www.fatnugsmag.com/cannabis-and-the-body-stretching-high-part-1/" },
  { date: "2026-01-19", publication: "Fat Nugs Magazine", series: "Cannabis + the Body", byline: "RN Collins", title: "Cannabis and the Body: Stretching High, Part 2", href: "https://www.fatnugsmag.com/cannabis-and-the-body-stretching-high-part-2/" },
  { date: "2026-01-26", publication: "Fat Nugs Magazine", series: "Cannabis + the Body", byline: "RN Collins", title: "Cannabis and the Body: Stretching High, Part 3", href: "https://www.fatnugsmag.com/cannabis-and-the-body-stretching-high-part-3/" },
  { date: "2026-02-06", publication: "Fat Nugs Magazine", series: "Culture + analysis", byline: "RN Collins", title: "Gucci’s The Tiger, Psychedelics, and Fashion", href: "https://www.fatnugsmag.com/guccis-the-tiger-psychedelics-and-fashion/" },
  { date: "2026-02-19", publication: "Fat Nugs Magazine", series: "Culture + analysis", byline: "RN Collins", title: "Entheogens as Cultural Technologies", href: "https://www.fatnugsmag.com/entheogens-as-cultural-technologies/" },
  { date: "2026-02-23", publication: "Fat Nugs Magazine", series: "Ask a Neuroscientist", byline: "RN Collins", title: "Cannabis as Vagus Nerve Medicine?", href: "https://www.fatnugsmag.com/ask-a-neuroscientist-cannabis-as-vagus-nerve-medicine/" },
  { date: "2026-03-03", publication: "Fat Nugs Magazine", series: "Ask a Neuroscientist", byline: "RN Collins", title: "Why Does Music Hit Different When You’re High?", href: "https://www.fatnugsmag.com/ask-a-neuroscientist-the-neuroscience-of-cannabis-and-sound/" },
  { date: "2026-03-23", publication: "Fat Nugs Magazine", series: "Ask a Neuroscientist", byline: "RN Collins", title: "Cannabis and Meditation", href: "https://www.fatnugsmag.com/ask-a-neuroscientist-cannabis-and-meditation/" },
  { date: "2026-05-22", publication: "Fat Nugs Magazine", series: "Ask a Neuroscientist", byline: "RN Collins", title: "Set, Setting, and Structure in Psychedelic Therapy Spaces", href: "https://www.fatnugsmag.com/ask-a-neuroscientist-set-setting-and-structure-in-psychedelic-therapy-spaces/" },
  { date: "2026-03-09", publication: "Fat Nugs Magazine", series: "Field reporting + Hawaiʻi", byline: "RN Collins", title: "Haven’t Done This Before: Three Days at the Hawaiʻi Cannabis Expo", href: "https://www.fatnugsmag.com/three-days-at-the-hawaii-cannabis-expo/" },
  { date: "2026-03-17", publication: "Fat Nugs Magazine", series: "Field reporting + Hawaiʻi", byline: "RN Collins", title: "Sovereign Ground: Cannabis, Land, and the Kingdom of Hawaiʻi", href: "https://www.fatnugsmag.com/cannabis-and-hawaiian-sovereignty/" },
  { date: "2026-07-16", publication: "Fat Nugs Magazine", series: "Field reporting + Hawaiʻi", byline: "RN Collins", title: "Every Gram Accounted For: Inside Hawaiʻi’s Seed-to-Sale Tracking System", href: "https://www.fatnugsmag.com/inside-hawaiis-seed-to-sale-tracking-system/" },
  { date: "2026-03-30", publication: "Fat Nugs Magazine", series: "Field reporting + Hawaiʻi", byline: "RN Collins", title: "Champions and Supporters: Why Hawaiʻi Still Can’t Legalize Cannabis", href: "https://www.fatnugsmag.com/champions-and-supporters-why-hawaii-still-cant-legalize-cannabis/" },
  { date: "2026-04-06", publication: "Fat Nugs Magazine", series: "Ask a Neuroscientist", byline: "RN Collins", title: "Does Whole Plant Medicine Matter for Cannabis and Psychedelics?", href: "https://www.fatnugsmag.com/ask-a-neuroscientist-does-whole-plant-medicine-matter-for-cannabis-and-psychedelics/" },
  { date: "2026-04-13", publication: "Fat Nugs Magazine", series: "Ask a Neuroscientist", byline: "RN Collins", title: "Cannabis and Sleep", href: "https://www.fatnugsmag.com/ask-a-neuroscientist-cannabis-and-sleep/" },
  { date: "2026-04-18", publication: "Fat Nugs Magazine", series: "Field reporting + Hawaiʻi", byline: "RN Collins", title: "Cannabis as a People’s Movement: A Story of Community", href: "https://www.fatnugsmag.com/cannabis-as-a-peoples-movement-a-story-of-community/" },
  { date: "2026-04-28", publication: "Fat Nugs Magazine", series: "Ask a Neuroscientist", byline: "RN Collins", title: "Cannabis and Grief", href: "https://www.fatnugsmag.com/ask-a-neuroscientist-cannabis-and-grief/" },
  { date: "2026-05-01", publication: "Fat Nugs Magazine", series: "Field reporting + Hawaiʻi", byline: "RN Collins", title: "Paradise in Limbo: Hawaiʻi’s Cannabis Journey and the Road That Keeps Closing", href: "https://www.fatnugsmag.com/paradise-in-limbo-hawaiis-cannabis-journey/" },
  { date: "2026-05-04", publication: "Fat Nugs Magazine", series: "Ask a Neuroscientist", byline: "RN Collins", title: "Cannabis in Nature", href: "https://www.fatnugsmag.com/ask-a-neuroscientist-cannabis-in-nature/" },
  { date: "2026-05-26", publication: "Fat Nugs Magazine", series: "Field reporting + Hawaiʻi", byline: "RN Collins", title: "Hawaiʻi’s Cannabis Market: What the State’s Own Data Reveals About a Billion-Dollar Opportunity", href: "https://www.fatnugsmag.com/hawaiis-cannabis-market/" },
  { date: "2026-06-01", publication: "Fat Nugs Magazine", series: "Field reporting + Hawaiʻi", byline: "RN Collins", title: "Growing Against the Grain: The Science of Cannabis Cultivation in Hawaiʻi’s Unforgiving Climate", href: "https://www.fatnugsmag.com/science-of-cannabis-cultivation-in-hawaii/" },
  { date: "2026-06-09", publication: "Fat Nugs Magazine", series: "Field reporting + Hawaiʻi", byline: "RN Collins", title: "Six Islands, One Plant: How Geography Shaped Hawaiʻi’s Cannabis Identity", href: "https://www.fatnugsmag.com/how-geography-shaped-hawaiis-cannabis-identity/" },
  { date: "2026-06-23", publication: "Fat Nugs Magazine", series: "Science, design + culture", byline: "RN Collins", title: "Building With Your Stash: Hempcrete and Mycelium Composites", href: "https://www.fatnugsmag.com/how-hempcrete-and-mycelium-composites-are-revolutionizing-architecture/" },
  { date: "2026-08-06", publication: "Fat Nugs Magazine", series: "Ask a Neuroscientist", byline: "RN Collins", title: "Cannabis and Migraines", href: "https://www.fatnugsmag.com/ask-a-neuroscientist-cannabis-and-migraines/" },
  { date: "2026-08-12", publication: "Fat Nugs Magazine", series: "Ask a Neuroscientist", byline: "RN Collins", title: "I Study Cannabis and Psychedelics for a Living. It Still Doesn’t Fix My Migraines", href: "https://www.fatnugsmag.com/ask-a-neuroscientist-what-science-tells-me-about-my-migraines/" },

  { date: "2025-11-19", publication: "Cannabis Law Report", series: "Psychedelics, rights + governance", byline: "Rayven-Nikkita (RN) Collins", title: "A Sacred Brew, a Legal Battle, and the Question of Rights in the Psychedelic Century", href: "https://cannabislaw.report/article-psychedelics-rights-setting-the-stage-author-rayven-nikkita-rn-collins/" },
  { date: "2025-11-27", publication: "Cannabis Law Report", series: "Psychedelics, rights + governance", byline: "RN Collins", title: "Is Access to Sacred Plants a Human Right?", href: "https://cannabislaw.report/article-is-access-to-sacred-plants-a-human-right/" },
  { date: "2025-12-05", publication: "Cannabis Law Report", series: "Psychedelics, rights + governance", byline: "RN Collins", title: "Access, Equity & the Future of Psychedelic Regulation", href: "https://cannabislaw.report/access-equity-the-future-of-psychedelic-regulation/" },
  { date: "2025-12-17", publication: "Cannabis Law Report", series: "Hemp prohibition + constitutional authority", byline: "RN Collins", title: "The Brewers Who Lost Everything: What Prohibition Teaches About Regulatory Takings", href: "https://cannabislaw.report/the-brewers-who-lost-everything-what-prohibition-teaches-about-regulatory-takings-when-america-banned-alcohol-brewery-owners-lost-millions-the-supreme-court-said-they-were-entitled-to-nothing-tod/" },
  { date: "2026-01-16", publication: "Cannabis Law Report", series: "Hemp prohibition + constitutional authority", byline: "RN Collins", title: "The Amendment That Wasn’t Necessary: Congress’s Statutory Authority to Prohibit", href: "https://cannabislaw.report/the-amendment-that-wasnt-necessary-congresss-statutory-authority-to-prohibit-the-eighteenth-amendment-was-a-political-choice-not-a-constitutional-requirement-congress-had-already-banned-alcoho/" },
  { date: "2026-01-23", publication: "Cannabis Law Report", series: "Hemp prohibition + constitutional authority", byline: "RN Collins", title: "What Hemp Businesses Can Actually Do: Legal and Political Strategies", href: "https://cannabislaw.report/what-hemp-businesses-can-actually-do-legal-and-political-strategies/" },
  { date: "2026-02-21", publication: "Cannabis Law Report", series: "Hemp prohibition + constitutional authority", byline: "RN Collins", title: "Big Alcohol’s Regulatory Capture Play: The Real Story Behind the Hemp Ban", href: "https://cannabislaw.report/big-alcohols-regulatory-capture-play-the-real-story-behind-the-hemp-ban/" },
  { date: "2026-03-06", publication: "Cannabis Law Report", series: "Audit + oversight reports", byline: "RN Williams / RN Collins", title: "Monitoring Consent Decrees in Cannabis Policing Reform", href: "https://cannabislaw.report/rn-williams-monitoring-consent-decrees-in-cannabis-policing-reform/" },
  { date: "2026-03-06", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Williams / RN Collins", title: "Digital, AI, and Psychedelic Convergence: What This Means for Regulators", href: "https://cannabislaw.report/rn-williams-series-2-no-1-of-14-articles-digital-ai-and-psychedelic-convergence-what-this-means-for-regulators/" },
  { date: "2026-03-10", publication: "Cannabis Law Report", series: "Audit + oversight reports", byline: "RN Collins", title: "Procurement Oversight in Cannabis Regulatory Bodies", href: "https://cannabislaw.report/contributor-rn-collins-procurement-oversight-in-cannabis-regulatory-bodies/" },
  { date: "2026-03-13", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Regulatory Clarity vs. Innovation Tension in Emerging Drug Classes", href: "https://cannabislaw.report/rn-collins-regulatory-clarity-vs-innovation-tension-in-emerging-drug-classes/" },
  { date: "2026-03-16", publication: "Cannabis Law Report", series: "Legislative briefs", byline: "RN Collins", title: "Bill Tracker: Cannabis Enforcement Reforms in 2026 State Legislatures", href: "https://cannabislaw.report/rn-collins-bill-tracker-cannabis-enforcement-reforms-in-2026-state-legislatures/" },
  { date: "2026-03-18", publication: "Cannabis Law Report", series: "Audit + oversight reports", byline: "RN Collins", title: "Compliance Review of Cannabis Enforcement Divisions", href: "https://cannabislaw.report/r-n-collins-compliance-review-of-cannabis-enforcement-divisions-an-audit-and-oversight-report/" },
  { date: "2026-03-19", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Model Regulatory Framework for State Psilocybin Programs", href: "https://cannabislaw.report/rn-collins-series-2-no-3-of-20-articles-model-regulatory-framework-for-state-psilocybin-programs-policy-reform-governance-oversight-series/" },
  { date: "2026-03-24", publication: "Cannabis Law Report", series: "Legislative briefs", byline: "RN Collins", title: "Constitutional Challenges to Cannabis Licensing Schemes", href: "https://cannabislaw.report/r-n-collins-constitutional-challenges-to-cannabis-licensing-schemes/" },
  { date: "2026-03-27", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Independent Oversight Structures for Psychedelic Service Centers", href: "https://cannabislaw.report/rn-collins-series-3-no-3-of-20-articles/" },
  { date: "2026-03-30", publication: "Cannabis Law Report", series: "Audit + oversight reports", byline: "RN Collins", title: "Equity Program Outcomes in State Cannabis Markets", href: "https://cannabislaw.report/r-n-collins-equity-program-outcomes-in-state-cannabis-markets-an-audit-and-oversight-report/" },
  { date: "2026-04-03", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Civil Rights Safeguards in Psychedelic Service Delivery Models", href: "https://cannabislaw.report/rn-collins-series-2-no-5-of-20-civil-rights-safeguards-in-psychedelic-service-delivery-models-policy-reform-governance-oversight-series/" },
  { date: "2026-04-05", publication: "Cannabis Law Report", series: "Legislative briefs", byline: "RN Collins", title: "Federal Schedule III and State Cannabis Systems", href: "https://cannabislaw.report/r-n-collins-federal-schedule-iii-and-state-cannabis-systems-legislative-brief-series/" },
  { date: "2026-04-10", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Governance Design for Psychedelic Authorities: Lessons from Gaming & Utilities Commissions", href: "https://cannabislaw.report/rn-collins-series-2-no-6-of-20-governance-design-for-psychedelic-authorities-lessons-from-gaming-utilities-commissions-policy-reform-governance-oversight-series/" },
  { date: "2026-04-13", publication: "Cannabis Law Report", series: "Legislative briefs", byline: "RN Collins", title: "Fiscal-Impact Analysis of Cannabis Regulatory Agencies", href: "https://cannabislaw.report/rn-collins-fiscal-impact-analysis-of-cannabis-regulatory-agencies-legislative-brief-series/" },
  { date: "2026-04-15", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Federal–State Tensions in Psychedelic Regulation: Where Preemption May Emerge", href: "https://cannabislaw.report/rn-collins-series-2-no-7-of-20-federal-state-tensions-in-psychedelic-regulation-where-preemption-may-emerge/" },
  { date: "2026-04-17", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "State Psilocybin Implementation Statutes", href: "https://cannabislaw.report/rn-collins-series-2-no-8-of-20-state-psilocybin-implementation-statutes/" },
  { date: "2026-04-20", publication: "Cannabis Law Report", series: "Audit + oversight reports", byline: "RN Collins", title: "Monitoring Consent Decrees in Cannabis Policing Reform", href: "https://cannabislaw.report/rn-collins-an-audit-and-oversight-report-monitoring-consent-decrees-in-cannabis-policing-reform/", note: "A later publication URL for the March 6 report." },
  { date: "2026-04-22", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Congressional Action on Psychedelics: Federal Scheduling & Agency Authority", href: "https://cannabislaw.report/rn-collins-series-2-no-9-congressional-action-on-psychedelics-federal-scheduling-agency-authority/" },
  { date: "2026-04-29", publication: "Cannabis Law Report", series: "Federal drug policy", byline: "RN Collins", title: "Federal Drug Policy, April 2026: The Operative Architecture of Cannabis Rescheduling", href: "https://cannabislaw.report/rn-collins-federal-drug-policy-april-2026-the-operative-architecture-of-cannabis-rescheduling-the-psychedelic-therapeutic-acceleration-directive-and-the-road-to-june-29/" },
  { date: "2026-04-30", publication: "Cannabis Law Report", series: "Federal drug policy", byline: "RN Collins", title: "Federal Drug Policy, April 2026: The Operative Architecture of Cannabis Rescheduling", href: "https://cannabislaw.report/rn-collins-federal-drug-policy-april-2026-the-operative-architecture-of-cannabis-rescheduling-the-psychedelic-therapeutic-acceleration-directive-and-the-road-to-june-29-2/", note: "Duplicate publication URL retained for archive completeness." },
  { date: "2026-04-30", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Veteran Access to State-Licensed Psychedelic Services", href: "https://cannabislaw.report/rn-collins-series-2-no-10-veteran-access-to-state-licensed-psychedelic-services-a-legal-gap-at-the-intersection-of-federal-employment-security-clearances-and-state-regulation/" },
  { date: "2026-05-08", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Risk-Based Auditing for New Drug Regulatory Bodies", href: "https://cannabislaw.report/rn-collins-series-2-no-11-risk-based-auditing-for-new-drug-regulatory-bodies/" },
  { date: "2026-05-11", publication: "Cannabis Law Report", series: "Audit + oversight reports", byline: "RN Collins", title: "Public Records Transparency in Cannabis Agencies", href: "https://cannabislaw.report/rn-collins-public-records-transparency-in-cannabis-agencies-audit-oversight-report-series/" },
  { date: "2026-05-13", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Ballot Initiative Governance Risks in Psychedelic Legalization", href: "https://cannabislaw.report/rn-collins-series-2-no-12-ballot-initiative-governance-risks-in-psychedelic-legalization-cannabis-law-report-legislative-brief-series/" },
  { date: "2026-05-13", publication: "Cannabis Law Report", series: "Legislative briefs", byline: "RN Collins", title: "Separation-of-Powers Issues in State Cannabis Authorities", href: "https://cannabislaw.report/rn-collins-separation-of-powers-issues-in-state-cannabis-authorities-legislative-brief-series/" },
  { date: "2026-05-22", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Tribal Sovereignty and Psychedelic Regulation", href: "https://cannabislaw.report/rn-collins-series-2-no-13-tribal-sovereignty-and-psychedelic-regulation-indian-country-jurisdiction-tribal-state-compacts-and-the-limits-of-state-licensing-frameworks/" },
  { date: "2026-05-29", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "The Economics of Regulated Psilocybin", href: "https://cannabislaw.report/rn-collins-series-2-no-14-the-economics-of-regulated-psilocybin-financial-viability-equity-mandates-and-the-sustainability-of-state-service-center-programs-cannabis-law-report-audit-style-rep/" },
  { date: "2026-06-05", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Facilitator Workforce Economics in State Psilocybin Programs", href: "https://cannabislaw.report/rn-collins-series-2-no-15-facilitator-workforce-economics-in-state-psilocybin-programs-supply-demand-mismatches-rural-access-deficits-and-training-pipeline-design-audit-style-reports-series/" },
  { date: "2026-06-12", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Compliance Review of Oregon’s Psilocybin Licensing System", href: "https://cannabislaw.report/rn-collins-series-2-no-16-compliance-review-of-oregons-psilocybin-licensing-system/" },
  { date: "2026-07-17", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Oversight Architecture in Psychedelic Regulation", href: "https://cannabislaw.report/rn-collins-series-2-no-17-oversight-architecture-in-psychedelic-regulation/" },
  { date: "2026-07-24", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Inspection & Enforcement Metrics in State Psychedelic Programs (2022–2026)", href: "https://cannabislaw.report/rn-collins-series-2-no-18-inspection-enforcement-metrics-in-state-psychedelic-programs-2022-2026/" },
  { date: "2026-07-31", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Designing Inspector-General Functions for Emerging Drug Agencies", href: "https://cannabislaw.report/rn-collins-series-2-no-19-designing-inspector-general-functions-for-emerging-drug-agencies/" },
  { date: "2026-08-07", publication: "Cannabis Law Report", series: "Psychedelic policy reform · Series 2", byline: "RN Collins", title: "Transparency Mechanisms in Psychedelic Oversight Agencies", href: "https://cannabislaw.report/rn-collins-series-2-no-20/" },

  { date: "2026-05-05", publication: "Cannabis Law Journal", series: "Republished edition", byline: "RN Collins", title: "Federal Drug Policy, April 2026: The Operative Architecture of Cannabis Rescheduling", href: "https://journal.cannabislawreport.com/rn-collins-federal-drug-policy-april-2026-the-operative-architecture-of-cannabis-rescheduling-the-psychedelic-therapeutic-acceleration-directive-and-the-road-to-june-29/", note: "Journal edition of work also published by Cannabis Law Report." },
  { date: "2026-06-02", publication: "Cannabis Law Journal", series: "Republished edition", byline: "RN Collins", title: "Separation-of-Powers Issues in State Cannabis Authorities", href: "https://journal.cannabislawreport.com/rn-collins-separation-of-powers-issues-in-state-cannabis-authorities-legislative-brief-series/", note: "Journal edition of work also published by Cannabis Law Report." },
  { date: "2026-06-02", publication: "Cannabis Law Journal", series: "Republished edition", byline: "RN Collins", title: "Tribal Sovereignty and Psychedelic Regulation", href: "https://journal.cannabislawreport.com/rn-collins-series-2-no-13-tribal-sovereignty-and-psychedelic-regulation-indian-country-jurisdiction-tribal-state-compacts-and-the-limits-of-state-licensing-frameworks/", note: "Journal edition of work also published by Cannabis Law Report." },
];

export const publicationCounts = publicationArchive.reduce<Record<string, number>>(
  (counts, article) => {
    counts[article.publication] = (counts[article.publication] ?? 0) + 1;
    return counts;
  },
  {},
);
