export const propertyKinds = ["umbrella-practice", "initiative", "program", "product", "publication", "method", "recipient-room", "case-study", "archive"] as const;
export type PropertyKind = (typeof propertyKinds)[number];
export type LifecycleStatus = "active" | "in-development" | "planned" | "paused" | "archived" | "private";
export type ReadinessStatus = "not-applicable" | "concept" | "prototype" | "self-serve-ready" | "delivery-ready" | "released";
export type SiteProperty = { id:string; name:string; shortName:string; kind:PropertyKind; ownerId:string|null; lifecycle:LifecycleStatus; readiness:ReadinessStatus; purpose:string; destination:string|null; preservedUrls:readonly string[]; public:boolean; indexable:boolean; evidenceBoundary:string|null };

export const siteProperties = [
  { id:"rn", name:"Rayven-Nikkita (RN) Collins", shortName:"RN", kind:"umbrella-practice", ownerId:null, lifecycle:"active", readiness:"not-applicable", purpose:"The canonical identity and container for RN's practice and bodies of work.", destination:"/", preservedUrls:["/"], public:true, indexable:true, evidenceBoundary:null },
  { id:"aloha-ai", name:"Aloha AI", shortName:"Aloha AI", kind:"initiative", ownerId:"rn", lifecycle:"in-development", readiness:"not-applicable", purpose:"AI-specific education, decision support, tools, and implementation work held by RN.", destination:"/initiatives/aloha-ai", preservedUrls:["/work/aloha-ai","https://aloha-ai-consulting.vercel.app/"], public:true, indexable:true, evidenceBoundary:"Individual products retain separate readiness, evidence, and fulfillment status." },
  { id:"institutions-of-one", name:"Institutions of One", shortName:"Institutions of One", kind:"initiative", ownerId:"rn", lifecycle:"in-development", readiness:"not-applicable", purpose:"Research and systems concerning ownership, portability, independent practice, and institutional legibility.", destination:"/initiatives/institutions-of-one", preservedUrls:["/work/ownership-platform"], public:true, indexable:true, evidenceBoundary:"Institutions of One is a separate sibling initiative from NSAG. It concerns ownership, portability, independent practice, and institutional legibility—not nervous-system-aware governance." },
  { id:"nsag", name:"Neurocognitive Systems Advisory Group", shortName:"NSAG", kind:"initiative", ownerId:"rn", lifecycle:"in-development", readiness:"not-applicable", purpose:"Nervous-system-aware governance and research-led institutional design.", destination:"/initiatives/nsag", preservedUrls:["/work/neurocognitive-systems-advisory-group"], public:true, indexable:true, evidenceBoundary:"Framework, assessment, applied-system, and outcome claims retain their case-study evidence boundaries." },
  { id:"the-polymath", name:"The Polymath", shortName:"The Polymath", kind:"publication", ownerId:"rn", lifecycle:"active", readiness:"not-applicable", purpose:"RN's editorial publishing property.", destination:null, preservedUrls:[], public:false, indexable:false, evidenceBoundary:"A verified canonical publication URL is required before this property is linked publicly." },
  { id:"for-culturalyst", name:"For Culturalyst", shortName:"For Culturalyst", kind:"recipient-room", ownerId:"rn", lifecycle:"active", readiness:"not-applicable", purpose:"Organization-specific research, evidence, opportunity mapping, and conversation preparation.", destination:"/for/culturalyst", preservedUrls:["/for/culturalyst","/for/culturalyst/work","/for/culturalyst/opportunities","/for/culturalyst/conversation"], public:true, indexable:true, evidenceBoundary:"Independently initiated pre-proposal work; not commissioned by or produced on behalf of Culturalyst." },
] as const satisfies readonly SiteProperty[];

export function getSiteProperty(id:string){ return siteProperties.find((property)=>property.id===id) }
export function assertSiteProperties(properties:readonly SiteProperty[]):void{ const ids=new Set<string>(); const destinations=new Set<string>(); for(const property of properties){ if(ids.has(property.id))throw new Error(`Duplicate property id: ${property.id}`); ids.add(property.id); if(!property.public&&property.indexable)throw new Error(`Non-public property cannot be indexable: ${property.id}`); if(property.destination?.startsWith("/")){if(destinations.has(property.destination))throw new Error(`Duplicate destination: ${property.destination}`);destinations.add(property.destination)}} for(const property of properties){if(property.ownerId&&!ids.has(property.ownerId))throw new Error(`Unknown owner: ${property.ownerId}`)}}
assertSiteProperties(siteProperties);
